/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import javax.swing.JButton;
import Modelo.ModeloRefeicoes;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import static com.oracle.jrockit.jfr.ContentType.Address;
import java.awt.Color;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.PasswordAuthentication;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.activation.DataHandler;
import javax.activation.FileDataSource;
import javax.mail.Address;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.ChartUtilities;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Alex
 */
public class FrmRelatorio extends javax.swing.JFrame {

    ModeloRefeicoes Refeicao;
    NumberFormat z;
    String caminho;
    SimpleDateFormat dt;
    String DataInicial, DataFinal;
   
    /**
     * Creates new form FrmRelatório
     */
    public FrmRelatorio() {
        z = NumberFormat.getCurrencyInstance();
        this.setIconImage(new ImageIcon(getClass().getResource("/imagem/icone.png")).getImage());
        initComponents();
        Refeicao = new ModeloRefeicoes();
        dt = new SimpleDateFormat("dd/MM/yyyy");
        JdcFim.setDate(new java.util.Date());  
        JdcInicio.setDate(new java.util.Date());  
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jMenuItem1 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        lblbLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        Jlbl50 = new javax.swing.JLabel();
        Jlabel70 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        JdcInicio = new com.toedter.calendar.JDateChooser();
        JdcFim = new com.toedter.calendar.JDateChooser();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        lblDiaria = new javax.swing.JLabel();
        lblQuantidadeApartamentos = new javax.swing.JLabel();
        lblQuantidadeFrigobar = new javax.swing.JLabel();
        lblQuantidadeAdultos = new javax.swing.JLabel();
        lblQuantidadeCriancas = new javax.swing.JLabel();
        lblQuantidadeDesconto = new javax.swing.JLabel();
        lblTotalCriancas = new javax.swing.JLabel();
        lblTotalFrigobar = new javax.swing.JLabel();
        lblTotalHospedagem = new javax.swing.JLabel();
        lblQdtCafeInfantil = new javax.swing.JLabel();
        lblQdtCafeAdulto = new javax.swing.JLabel();
        lblQdtCafeTotal = new javax.swing.JLabel();
        lblTotalGeralCafe = new javax.swing.JLabel();
        lblQuantidadeExecutivoAdulto = new javax.swing.JLabel();
        lblQuantidadeExecutivoInfantil = new javax.swing.JLabel();
        lblQuantidadeExecutivoTotal = new javax.swing.JLabel();
        lblTotalExecutivo = new javax.swing.JLabel();
        lblQdtAlacarteAdulto = new javax.swing.JLabel();
        lblQdtAlacarteInfantil = new javax.swing.JLabel();
        lblQdtAlacarteTotal = new javax.swing.JLabel();
        lblQdtAlacarteGeral = new javax.swing.JLabel();
        lblQuantidadeSelfServiceAdulto = new javax.swing.JLabel();
        lblQuantidadeSelfServiceInfantil = new javax.swing.JLabel();
        lblQuantidadeSelfServiceTotal = new javax.swing.JLabel();
        lblSelfServiceTotal = new javax.swing.JLabel();
        lblQuantidadeRefeicoesGeral = new javax.swing.JLabel();
        lblTotalGeralRefeicoes = new javax.swing.JLabel();
        lblTotalGeralSalao = new javax.swing.JLabel();
        lblValorSalao = new javax.swing.JLabel();
        lblValorExtras = new javax.swing.JLabel();
        lblSalaoTotalItens = new javax.swing.JLabel();
        BtnGeraPDf = new javax.swing.JButton();
        jLabel50 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        lblTotalAdultos = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        lblTotalPacote = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        lblTotalDesconto = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        txtDesconto = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        lblTotalGeral = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        lblFundo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Hospedagem");

        jLabel48.setText("jLabel39");

        jMenuItem1.setText("jMenuItem1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblbLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/logonovoo.png"))); // NOI18N
        getContentPane().add(lblbLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1127, 150));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hospedagem");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 1150, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Refeições");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 1150, -1));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Total Geral:");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 690, 1150, -1));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 445, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Quantidade de Diárias:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Quantidade de Apartamentos:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Quantidade de Frigobares:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Quantidade de Crianças:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Quantidade de Desconto:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Valor Total:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 250, -1, 50));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Total Frigobar:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 300, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Total Crianças:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 240, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Qdt de Café Adulto:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Qdt de Café Infantil:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Total Quantidade Café:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("Total Geral Café:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Qdt de Executivo Adulto:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Qdt de Executivo Infantil:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("Total Quantidade Executivo:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("Total Geral Executivo:");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("Qdt de A LaCarte Adulto:");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("Qdt de A LaCarte Infantil:");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 410, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setText("Total Quantidade A LaCarte:");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setText("Total Geral A LaCarte:");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel26.setText("Qdt de SelfService Adulto:");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 380, -1, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel27.setText("Qdt de SelfService Infantil:");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 410, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel28.setText("Total Quantidade SelfService:");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 440, -1, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel29.setText("Total Geral SelfService:");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 470, -1, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel30.setText("Total Geral:");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 630, -1, -1));

        Jlbl50.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Jlbl50.setText("Valor Extras");
        getContentPane().add(Jlbl50, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 630, -1, -1));

        Jlabel70.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Jlabel70.setText("Total Itens");
        getContentPane().add(Jlabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 600, -1, -1));

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel33.setText("Valor Salão");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 600, -1, -1));

        JdcInicio.setOpaque(false);
        JdcInicio.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                JdcInicioPropertyChange(evt);
            }
        });
        getContentPane().add(JdcInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 152, 130, -1));

        JdcFim.setOpaque(false);
        JdcFim.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                JdcFimPropertyChange(evt);
            }
        });
        getContentPane().add(JdcFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 152, 130, -1));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel34.setText("Check In");
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel35.setText("Check Out");
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 160, -1, -1));

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel36.setText("Quantidade de Adultos:");
        getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, -1, -1));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel37.setText("Total Quantidades Geral :");
        getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, -1, -1));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel38.setText("Total Geral :");
        getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, -1, -1));

        lblDiaria.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDiaria.setText(" ");
        getContentPane().add(lblDiaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 99, -1));

        lblQuantidadeApartamentos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblQuantidadeApartamentos.setText(" ");
        getContentPane().add(lblQuantidadeApartamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 99, -1));

        lblQuantidadeFrigobar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblQuantidadeFrigobar.setText(" ");
        getContentPane().add(lblQuantidadeFrigobar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 99, -1));

        lblQuantidadeAdultos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblQuantidadeAdultos.setText(" ");
        getContentPane().add(lblQuantidadeAdultos, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, 99, -1));

        lblQuantidadeCriancas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblQuantidadeCriancas.setText(" ");
        getContentPane().add(lblQuantidadeCriancas, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 270, 99, -1));

        lblQuantidadeDesconto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblQuantidadeDesconto.setText(" ");
        getContentPane().add(lblQuantidadeDesconto, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, 99, -1));

        lblTotalCriancas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTotalCriancas.setText(" ");
        getContentPane().add(lblTotalCriancas, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 240, 90, -1));

        lblTotalFrigobar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTotalFrigobar.setText(" ");
        getContentPane().add(lblTotalFrigobar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 300, 90, -1));

        lblTotalHospedagem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTotalHospedagem.setText(" ");
        getContentPane().add(lblTotalHospedagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 250, 90, 50));

        lblQdtCafeInfantil.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblQdtCafeInfantil.setText(" ");
        getContentPane().add(lblQdtCafeInfantil, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 99, -1));

        lblQdtCafeAdulto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblQdtCafeAdulto.setText(" ");
        getContentPane().add(lblQdtCafeAdulto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 99, -1));

        lblQdtCafeTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblQdtCafeTotal.setText(" ");
        getContentPane().add(lblQdtCafeTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 100, -1));

        lblTotalGeralCafe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTotalGeralCafe.setText(" ");
        getContentPane().add(lblTotalGeralCafe, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 99, -1));

        lblQuantidadeExecutivoAdulto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblQuantidadeExecutivoAdulto.setText(" ");
        getContentPane().add(lblQuantidadeExecutivoAdulto, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, 99, -1));

        lblQuantidadeExecutivoInfantil.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblQuantidadeExecutivoInfantil.setText(" ");
        getContentPane().add(lblQuantidadeExecutivoInfantil, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 410, 99, -1));

        lblQuantidadeExecutivoTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblQuantidadeExecutivoTotal.setText(" ");
        getContentPane().add(lblQuantidadeExecutivoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, 99, -1));

        lblTotalExecutivo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTotalExecutivo.setText(" ");
        getContentPane().add(lblTotalExecutivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 470, 99, -1));

        lblQdtAlacarteAdulto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblQdtAlacarteAdulto.setText(" ");
        getContentPane().add(lblQdtAlacarteAdulto, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 380, 90, -1));

        lblQdtAlacarteInfantil.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblQdtAlacarteInfantil.setText(" ");
        getContentPane().add(lblQdtAlacarteInfantil, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 410, 99, -1));

        lblQdtAlacarteTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblQdtAlacarteTotal.setText(" ");
        getContentPane().add(lblQdtAlacarteTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 440, 99, -1));

        lblQdtAlacarteGeral.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblQdtAlacarteGeral.setText(" ");
        getContentPane().add(lblQdtAlacarteGeral, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 470, 99, -1));

        lblQuantidadeSelfServiceAdulto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblQuantidadeSelfServiceAdulto.setText(" ");
        getContentPane().add(lblQuantidadeSelfServiceAdulto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 380, 99, -1));

        lblQuantidadeSelfServiceInfantil.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblQuantidadeSelfServiceInfantil.setText(" ");
        getContentPane().add(lblQuantidadeSelfServiceInfantil, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 410, 99, -1));

        lblQuantidadeSelfServiceTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblQuantidadeSelfServiceTotal.setText(" ");
        getContentPane().add(lblQuantidadeSelfServiceTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 440, 99, -1));

        lblSelfServiceTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSelfServiceTotal.setText(" ");
        getContentPane().add(lblSelfServiceTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 470, 99, -1));

        lblQuantidadeRefeicoesGeral.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblQuantidadeRefeicoesGeral.setText(" ");
        getContentPane().add(lblQuantidadeRefeicoesGeral, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 510, 90, -1));

        lblTotalGeralRefeicoes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTotalGeralRefeicoes.setText(" ");
        getContentPane().add(lblTotalGeralRefeicoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 510, 99, -1));

        lblTotalGeralSalao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTotalGeralSalao.setText(" ");
        getContentPane().add(lblTotalGeralSalao, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 630, 99, -1));

        lblValorSalao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblValorSalao.setText(" ");
        getContentPane().add(lblValorSalao, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 600, 99, -1));

        lblValorExtras.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblValorExtras.setText(" ");
        getContentPane().add(lblValorExtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 630, 99, -1));

        lblSalaoTotalItens.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSalaoTotalItens.setText(" ");
        getContentPane().add(lblSalaoTotalItens, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 600, 99, -1));

        BtnGeraPDf.setText("Gerar PDF");
        BtnGeraPDf.setOpaque(false);
        BtnGeraPDf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGeraPDfActionPerformed(evt);
            }
        });
        getContentPane().add(BtnGeraPDf, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 820, 136, 40));

        jLabel50.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel50.setText("Salão");
        jLabel50.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 1150, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel31.setText("Total Adultos:");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 270, -1, -1));

        lblTotalAdultos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTotalAdultos.setText(" ");
        getContentPane().add(lblTotalAdultos, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 270, 90, -1));

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setOpaque(false);

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel32.setText("Total:");

        lblTotalPacote.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotalPacote.setText(" ");

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel40.setText("Total Desconto:");

        lblTotalDesconto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotalDesconto.setText(" ");

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel42.setText("Desconto (%):");

        txtDesconto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtDesconto.setText("0");

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel43.setText("Total Geral:");

        lblTotalGeral.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotalGeral.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40)
                    .addComponent(jLabel32))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTotalPacote, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(lblTotalDesconto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel42)
                    .addComponent(jLabel43))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTotalGeral, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .addComponent(txtDesconto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(lblTotalPacote)
                    .addComponent(jLabel42)
                    .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(lblTotalDesconto)
                    .addComponent(jLabel43)
                    .addComponent(lblTotalGeral))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 730, 540, 80));

        btnCalcular.setText("Calcular");
        btnCalcular.setOpaque(false);
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 820, 136, 40));

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Hotels.png"))); // NOI18N
        lblFundo.setText(" ");
        getContentPane().add(lblFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -60, 1150, 990));

        jMenu1.setText("Cálculo Refeições");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cálculo Diárias");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Cálculo de Salão");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu5.setText("Sobre");
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1162, 927));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnGeraPDfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGeraPDfActionPerformed
        AtualizaRelatorio();
        
        
        
//
// DefaultPieDataset dpd = new DefaultPieDataset();
//        dpd.setValue("Promoções", GPromocoes);
//        dpd.setValue("Pedidos", GPedidos);
//        dpd.setValue("Compras", GCompras);
//        dpd.setValue("Funcionários", GFuncionarios);
//        dpd.setValue("Despesas", GDespesas);
//
//        JFreeChart grafico = ChartFactory.createPieChart("Resumo por setor", dpd, true, true, false);
//
//        ChartPanel chartPanel = new ChartPanel(grafico);
//
//        try {
//            ChartUtilities.saveChartAsJPEG(new java.io.File("G:/PizzaSetor.jpg"), grafico, 700, 600);
//        } catch (IOException ex) {
//            Logger.getLogger(FrmRelatorio.class.getName()).log(Level.SEVERE, null, ex);
//        }
//
//        DefaultPieDataset dpd1 = new DefaultPieDataset();
//        dpd1.setValue("Total Despesas", GTotalDespesas);
//        dpd1.setValue("Total Receitas", GTotalReceitas);
//        dpd1.setValue("Total Geral", GTotalGeral);
//
//        JFreeChart grafico1 = ChartFactory.createPieChart("Resumo Geral", dpd1, true, true, false);
//
//        ChartPanel chartPanel1 = new ChartPanel(grafico1);
//
//        try {
//            ChartUtilities.saveChartAsJPEG(new java.io.File("G:/PizzaTotal.jpg"), grafico1, 700, 600);
//        } catch (IOException ex) {
//            Logger.getLogger(FrmRelatorio.class.getName()).log(Level.SEVERE, null, ex);
//        }
//
        File pdf = null;
        JFileChooser chooser = null;
//int res = chooser.showSaveDialog(home);
        try {
            pdf = File.createTempFile("NomedoArquivoSemExtensão", ".pdf");
        } catch (IOException e1) {
            e1.printStackTrace();
        }
//
//Geração do arquivo
        chooser = new JFileChooser();
        chooser.setCurrentDirectory(pdf);
        chooser.setSelectedFile(pdf);

        javax.swing.filechooser.FileFilter filter = new javax.swing.filechooser.FileFilter() {

            public boolean accept(File f) {
                return f.isDirectory()
                        || f.getName().toLowerCase().endsWith(
                                ".pdf");
            }

            public String getDescription() {
                return "(*.pdf)";
                // return "(*.xls)";  
            }

        };
        chooser.addChoosableFileFilter(filter);
        chooser.setAcceptAllFileFilterUsed(false);
        chooser.setMultiSelectionEnabled(false);

        caminho = "";

        int retorno = chooser.showSaveDialog(null);
        if (retorno == JFileChooser.APPROVE_OPTION) {
            caminho = chooser.getSelectedFile().getAbsolutePath();
        }
//
        if (!caminho.equals("")) {
            boolean ok = pdf.renameTo(new File(caminho));
            if (ok) {
                try {
                            gerapdf(DataInicial,DataFinal,lblTotalGeralSalao.getText(), lblTotalHospedagem.getText(),
                                    lblTotalGeralRefeicoes.getText(), lblTotalDesconto.getText(), lblTotalPacote.getText(),
                                    lblTotalGeral.getText());
                    
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Erro ao salvar documento" + e);
                }
            }
        }
//            
//

//        if (!caminho.equals("")) {
//            this.setAlwaysOnTop(false);
//            int opcao = JOptionPane.showConfirmDialog(null, "Enviar Relatório por Email?", "Sair", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
//
//            if (opcao == JOptionPane.NO_OPTION) {
//                JOptionPane.showMessageDialog(this, "Envio de email cancelado.");
//                this.setAlwaysOnTop(true);
//            } else if (opcao == JOptionPane.YES_OPTION) {
//                this.setAlwaysOnTop(false);
//                for (int e = 0; e <= 3; e++) {
//                    destinatario = JOptionPane.showInputDialog(this, "Nome do Destinatário:", "Destinatário", JOptionPane.PLAIN_MESSAGE);
//
//                    if (destinatario.contains("@") && destinatario.contains(".")) {
//
//                        if (destinatario == null || destinatario.equals("")) {
//                            JOptionPane.showMessageDialog(this, "Você não inseriu um e-mail válido.");
//                            if (e == 2) {
//                                JOptionPane.showMessageDialog(this, "Email não enviado.");
//                                break;
//
//                            }
//                        } else {
//                            try {
//                                EnviarEmail();
//                               
//                                    JOptionPane.showMessageDialog(this, "Email Enviado com Sucesso");
//                                    
//                                    this.setAlwaysOnTop(true);
//                                    break;
//                                
//
//                            } catch (Exception ex) {
//                                JOptionPane.showMessageDialog(this, "O Email não foi enviado.\n Motivo: " + ex);
//                                break;
//                            }
//
//                        }
//
//                    } else {
//                        JOptionPane.showMessageDialog(this, "Destinatário Inválido");
//                    }
//
//                }

    }//GEN-LAST:event_BtnGeraPDfActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        new FrmRefeicoes().setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        new Frm_Hospedagem().setVisible(true);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        new frm_Eventos().setVisible(true);
    }//GEN-LAST:event_jMenu3MouseClicked

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        DataFinal = dt.format(JdcFim.getDate()); 
        
        DataInicial = dt.format(JdcInicio.getDate());
        
        System.out.println(DataFinal);
        System.out.println(DataInicial);
        
        TotalGeral = FrmRefeicoes.RelTotalGeral + Frm_Hospedagem.VlrTotal + frm_Eventos.totalSalao;

        lblTotalPacote.setText(z.format(TotalGeral));

        TotalDesconto = (TotalGeral * (Double.parseDouble(txtDesconto.getText())) / 100);

        lblTotalDesconto.setText(z.format(TotalDesconto));

        TotalPacote = TotalGeral - TotalDesconto;

        lblTotalGeral.setText(z.format(TotalPacote));

    }//GEN-LAST:event_btnCalcularActionPerformed

    private void JdcInicioPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_JdcInicioPropertyChange

    // TODO add your handling code here:
    }//GEN-LAST:event_JdcInicioPropertyChange

    private void JdcFimPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_JdcFimPropertyChange
           // TODO add your handling code here:
    }//GEN-LAST:event_JdcFimPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRelatorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGeraPDf;
    private com.toedter.calendar.JDateChooser JdcFim;
    private com.toedter.calendar.JDateChooser JdcInicio;
    private javax.swing.JLabel Jlabel70;
    private javax.swing.JLabel Jlbl50;
    public static javax.swing.JButton btnCalcular;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDiaria;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblQdtAlacarteAdulto;
    private javax.swing.JLabel lblQdtAlacarteGeral;
    private javax.swing.JLabel lblQdtAlacarteInfantil;
    private javax.swing.JLabel lblQdtAlacarteTotal;
    private javax.swing.JLabel lblQdtCafeAdulto;
    private javax.swing.JLabel lblQdtCafeInfantil;
    private javax.swing.JLabel lblQdtCafeTotal;
    private javax.swing.JLabel lblQuantidadeAdultos;
    private javax.swing.JLabel lblQuantidadeApartamentos;
    private javax.swing.JLabel lblQuantidadeCriancas;
    private javax.swing.JLabel lblQuantidadeDesconto;
    private javax.swing.JLabel lblQuantidadeExecutivoAdulto;
    private javax.swing.JLabel lblQuantidadeExecutivoInfantil;
    private javax.swing.JLabel lblQuantidadeExecutivoTotal;
    private javax.swing.JLabel lblQuantidadeFrigobar;
    private javax.swing.JLabel lblQuantidadeRefeicoesGeral;
    private javax.swing.JLabel lblQuantidadeSelfServiceAdulto;
    private javax.swing.JLabel lblQuantidadeSelfServiceInfantil;
    private javax.swing.JLabel lblQuantidadeSelfServiceTotal;
    private javax.swing.JLabel lblSalaoTotalItens;
    private javax.swing.JLabel lblSelfServiceTotal;
    private javax.swing.JLabel lblTotalAdultos;
    private javax.swing.JLabel lblTotalCriancas;
    private javax.swing.JLabel lblTotalDesconto;
    private javax.swing.JLabel lblTotalExecutivo;
    private javax.swing.JLabel lblTotalFrigobar;
    private javax.swing.JLabel lblTotalGeral;
    private javax.swing.JLabel lblTotalGeralCafe;
    private javax.swing.JLabel lblTotalGeralRefeicoes;
    private javax.swing.JLabel lblTotalGeralSalao;
    private javax.swing.JLabel lblTotalHospedagem;
    private javax.swing.JLabel lblTotalPacote;
    private javax.swing.JLabel lblValorExtras;
    private javax.swing.JLabel lblValorSalao;
    private javax.swing.JLabel lblbLogo;
    private javax.swing.JTextField txtDesconto;
    // End of variables declaration//GEN-END:variables

    public static int binario = 0;
    public static double TotalGeral, TotalDesconto, TotalPacote;
    String NomeRelatorio, destinatario;
    

    public void AtualizaRelatorio() {
        
        DataFinal = dt.format(JdcFim.getDate()); 
        
        DataInicial = dt.format(JdcInicio.getDate());
        
//ReFeições

        lblQdtCafeAdulto.setText(Refeicao.getQuantidadeCafeAdulto() + "");

        lblQdtCafeAdulto.setText(FrmRefeicoes.QuantidadeCafeAdulto + "");
        lblQdtCafeInfantil.setText(FrmRefeicoes.QuantidadeCafeInfantil + "");
        lblQdtCafeTotal.setText(FrmRefeicoes.QuantidadeCafeTotal + "");
        lblTotalGeralCafe.setText(FrmRefeicoes.RelTotalCafe + "");

        lblQuantidadeExecutivoAdulto.setText(FrmRefeicoes.QuantidadeExecutivoAdulto + "");
        lblQuantidadeExecutivoInfantil.setText(FrmRefeicoes.QuantidadeExecutivoInfantil + "");
        lblQuantidadeExecutivoTotal.setText(FrmRefeicoes.QuantidadeExecutivoTotal + "");
        lblTotalExecutivo.setText(FrmRefeicoes.RelTotalExecutivo + "");

        lblQdtAlacarteAdulto.setText(FrmRefeicoes.QuantidadeAlacarteAdulto + "");
        lblQdtAlacarteInfantil.setText(FrmRefeicoes.QuantidadeAlacarteInfantil + "");
        lblQdtAlacarteTotal.setText(FrmRefeicoes.QuantidadeAlacarteTotal + "");
        lblQdtAlacarteGeral.setText(FrmRefeicoes.RelTotalAlacarte + "");

        lblQuantidadeSelfServiceAdulto.setText(FrmRefeicoes.QuantidadeSelfServiceAdult + "");
        lblQuantidadeSelfServiceInfantil.setText(FrmRefeicoes.QuantidadeSelfServiceInfantil + "");
        lblQuantidadeSelfServiceTotal.setText(FrmRefeicoes.QuantidadeSelfServiceTotal + "");
        lblSelfServiceTotal.setText(FrmRefeicoes.RelTotalSelfService + "");

        lblTotalGeralRefeicoes.setText(FrmRefeicoes.RelTotalGeral + "");
        lblQuantidadeRefeicoesGeral.setText(FrmRefeicoes.QuantidadeTotal + "");

//Hospedagens
        lblDiaria.setText(Frm_Hospedagem.diaria + "");
        lblQuantidadeApartamentos.setText(Frm_Hospedagem.QdtApartamentos + "");
        lblQuantidadeFrigobar.setText(Frm_Hospedagem.qtdfrigobar + "");
        lblQuantidadeAdultos.setText(null);
        lblQuantidadeCriancas.setText(Frm_Hospedagem.QtdCriancas + "");
        lblQuantidadeDesconto.setText(Frm_Hospedagem.PorcentagemDesconto);
        lblTotalCriancas.setText(Frm_Hospedagem.TotalCriancas + "");
        lblTotalAdultos.setText(null);
        lblTotalFrigobar.setText(Frm_Hospedagem.frigobar + "");
        lblTotalHospedagem.setText(Frm_Hospedagem.VlrTotal + "");

//Salao
        lblValorSalao.setText(null);
        lblValorExtras.setText(null);
        lblSalaoTotalItens.setText(null);
        lblTotalGeralSalao.setText(z.format(frm_Eventos.totalSalao));

    }
    
    
    public void AtualizaRELL (FrmRefeicoes frmRe, int numero)
    {
        
        if (numero ==1)
        {
        
     DataFinal = dt.format(JdcFim.getDate()); 
        
        DataInicial = dt.format(JdcInicio.getDate());
        
//ReFeições

        lblQdtCafeAdulto.setText(Refeicao.getQuantidadeCafeAdulto() + "");

        lblQdtCafeAdulto.setText(FrmRefeicoes.QuantidadeCafeAdulto + "");
        lblQdtCafeInfantil.setText(FrmRefeicoes.QuantidadeCafeInfantil + "");
        lblQdtCafeTotal.setText(FrmRefeicoes.QuantidadeCafeTotal + "");
        lblTotalGeralCafe.setText(FrmRefeicoes.RelTotalCafe + "");

        lblQuantidadeExecutivoAdulto.setText(FrmRefeicoes.QuantidadeExecutivoAdulto + "");
        lblQuantidadeExecutivoInfantil.setText(FrmRefeicoes.QuantidadeExecutivoInfantil + "");
        lblQuantidadeExecutivoTotal.setText(FrmRefeicoes.QuantidadeExecutivoTotal + "");
        lblTotalExecutivo.setText(FrmRefeicoes.RelTotalExecutivo + "");

        lblQdtAlacarteAdulto.setText(FrmRefeicoes.QuantidadeAlacarteAdulto + "");
        lblQdtAlacarteInfantil.setText(FrmRefeicoes.QuantidadeAlacarteInfantil + "");
        lblQdtAlacarteTotal.setText(FrmRefeicoes.QuantidadeAlacarteTotal + "");
        lblQdtAlacarteGeral.setText(FrmRefeicoes.RelTotalAlacarte + "");

        lblQuantidadeSelfServiceAdulto.setText(FrmRefeicoes.QuantidadeSelfServiceAdult + "");
        lblQuantidadeSelfServiceInfantil.setText(FrmRefeicoes.QuantidadeSelfServiceInfantil + "");
        lblQuantidadeSelfServiceTotal.setText(FrmRefeicoes.QuantidadeSelfServiceTotal + "");
        lblSelfServiceTotal.setText(FrmRefeicoes.RelTotalSelfService + "");

        lblTotalGeralRefeicoes.setText(FrmRefeicoes.RelTotalGeral + "");
        lblQuantidadeRefeicoesGeral.setText(FrmRefeicoes.QuantidadeTotal + "");

//Hospedagens
        lblDiaria.setText(Frm_Hospedagem.diaria + "");
        lblQuantidadeApartamentos.setText(Frm_Hospedagem.QdtApartamentos + "");
        lblQuantidadeFrigobar.setText(Frm_Hospedagem.qtdfrigobar + "");
        lblQuantidadeAdultos.setText(null);
        lblQuantidadeCriancas.setText(Frm_Hospedagem.QtdCriancas + "");
        lblQuantidadeDesconto.setText(Frm_Hospedagem.PorcentagemDesconto);
        lblTotalCriancas.setText(Frm_Hospedagem.TotalCriancas + "");
        lblTotalAdultos.setText(null);
        lblTotalFrigobar.setText(Frm_Hospedagem.frigobar + "");
        lblTotalHospedagem.setText(Frm_Hospedagem.VlrTotal + "");

//Salao
        lblValorSalao.setText(null);
        lblValorExtras.setText(null);
        lblSalaoTotalItens.setText(null);
        lblTotalGeralSalao.setText(z.format(frm_Eventos.totalSalao));
    
        }
    
    }
    
    

    public void gerapdf(String dataInicial, String dataFinal, String TotalSalao, String TotalHospedagem, String TotalRefeicoes,
            String TotalDesconto, String TotalPacote, String TotalGeral) {

        // cria o documento vazio 
        Document DocumentPdf = new Document();

        try {

            // Criar uma nova Cor
            Color Laranja = new Color(242, 184, 171);

            //Criar um estilo de fonte para o Título
            Font h1 = new Font(Font.FontFamily.COURIER, 36, Font.BOLD);
            Font h2 = new Font(Font.FontFamily.COURIER, 25, Font.BOLD);
            Font h3 = new Font(Font.FontFamily.COURIER, 18, Font.BOLD);

            // Cria uma instancia e dá o nome para o pdf    
            // PdfWriter.getInstance(DocumentPdf, new FileOutputStream("../Giovanellis/Relatorios/" + NomeRelatorio + ".pdf"));
            PdfWriter.getInstance(DocumentPdf, new FileOutputStream(caminho));
            // abrir o documento
            DocumentPdf.open();

            // Setar o tamanho da página
            DocumentPdf.setPageSize(PageSize.A4);

           

            // Mencionando a instância da Imagem
            Image Cabecalho = Image.getInstance("H:/logonovoo.png");

            //Setar o tamanho em pixels da imagem
            Cabecalho.scaleToFit(400, 200);

            //Centraliza a Imagem
            Cabecalho.setAlignment(Element.ALIGN_CENTER);

            // Adicionar a imagem ao PDF
            DocumentPdf.add(Cabecalho);
            
             //Adicionar Primeiro parágrago do Título
            Paragraph Titulo = new Paragraph("Descritivo do Pacote:", h2);
            Titulo.setAlignment(Element.ALIGN_CENTER);
            DocumentPdf.add(Titulo);

            Paragraph datas = new Paragraph("Check In: " + DataInicial + "  Check Out: " + DataFinal + "\n" + "\n", h3);
            datas.setAlignment(Element.ALIGN_CENTER);
            DocumentPdf.add(datas);

            Paragraph Setor = new Paragraph("Resumo por Setor:" + "\n" + "\n", h2);
            Setor.setAlignment(Element.ALIGN_CENTER);
            DocumentPdf.add(Setor);

            Paragraph Total = new Paragraph("\n Resumo Geral:", h2);
            Total.setAlignment(Element.ALIGN_CENTER);
            DocumentPdf.add(Total);

//            Paragraph DescritivoDespesa = new Paragraph("\n Total de Despesas: " + Prejuizo + "\n", h3);
//            DescritivoDespesa.setAlignment(Element.ALIGN_CENTER);
//            DocumentPdf.add(DescritivoDespesa);
//
//            Paragraph DescritivoReceitas = new Paragraph("Total de Receitas: " + Receita + "\n", h3);
//            DescritivoReceitas.setAlignment(Element.ALIGN_CENTER);
//            DocumentPdf.add(DescritivoReceitas);
//
//            Paragraph TotalGeralR = new Paragraph("Total Geral: " + Geral + "\n", h3);
//            TotalGeralR.setAlignment(Element.ALIGN_CENTER);
//            DocumentPdf.add(TotalGeralR);

            Paragraph Espaço = new Paragraph("\n\n");

            //Cria uma Nova Página
            DocumentPdf.newPage();

            DocumentPdf.add(Titulo);

            DocumentPdf.add(Espaço);

////            Image Grafico1 = Image.getInstance("G:/PizzaSetor.jpg");
//
//            Grafico1.scaleToFit(500, 300);
//
//            Grafico1.setAlignment(Element.ALIGN_CENTER);
//
//            Image Grafico2 = Image.getInstance("G:/PizzaTotal.jpg");
//
//            Grafico2.scaleToFit(500, 300);
//
//            Grafico2.setAlignment(Element.ALIGN_CENTER);
//
//            DocumentPdf.add(Grafico1);
//
//            DocumentPdf.add(Espaço);
//
//            DocumentPdf.add(Grafico2);

            JOptionPane.showMessageDialog(this, "Arquivo Gerado com Sucesso \nCaminho:" + caminho);
            this.setAlwaysOnTop(true);

        } catch (DocumentException e) {
            e.printStackTrace();
        } catch (IOException ioe) {
            ioe.printStackTrace();
        } finally {
            DocumentPdf.close();
        }

    }

    public void EnviarEmail() {

        Properties props = new Properties();
        /**
         * Parâmetros de conexão com servidor Gmail
         */
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.socketFactory.port", "465");
        props.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.port", "465");

        Session session = Session.getDefaultInstance(props,
                new javax.mail.Authenticator() {
                    protected javax.mail.PasswordAuthentication getPasswordAuthentication() {
                        return new javax.mail.PasswordAuthentication("EMail@Email", "Senha");
                    }
                });

        /**
         * Ativa Debug para sessão
         */
        session.setDebug(true);

        try {

            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress("seuemail@gmail.com")); //Remetente

            Address[] toUser = InternetAddress //Destinatário(s)
                    .parse(destinatario);

            message.setRecipients(Message.RecipientType.TO, toUser);
            message.setSubject("Giovaneli's Relatório's enviado pelo Java");//Assunto
            message.setText("Anexo do Giovaneli's Relatório's do período solicitado");

            FileDataSource source = new FileDataSource(
                    caminho);
            message.setDataHandler(new DataHandler(source));
            message.setFileName(source.getName());

            /**
             * Método para enviar a mensagem criada
             */
            Transport.send(message);

            // JOptionPane.showMessageDialog(null, "E-mail Enviado com Sucesso");
        } catch (MessagingException e) {
            throw new RuntimeException(e);

        }

    }
}
