/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Conexao.SqlServer;
import Modelo.ModeloTabelas;
import Modelo.modeloContatos;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Alex
 */
public class frmPrefeituras extends javax.swing.JFrame {
    
    SqlServer conecta;
    
    int pos = 0;
    int max;
    int i;

    /**
     * Creates new form frmPrefeituras
     */
    public frmPrefeituras() throws Exception {
        initComponents();
        OcultaCampos();
        conecta = new SqlServer();

       try {
            UIManager.setLookAndFeel("de.javasoft.plaf.synthetica.SyntheticaAluOxideLookAndFeel");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmPrefeituras.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(frmPrefeituras.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(frmPrefeituras.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(frmPrefeituras.class.getName()).log(Level.SEVERE, null, ex);
        }

        SwingUtilities.updateComponentTreeUI(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SelecioneGrupo = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePrefeituras = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        TxtLinhas = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        JcbEstado = new javax.swing.JComboBox();
        RdEstado = new javax.swing.JRadioButton();
        RdCidade = new javax.swing.JRadioButton();
        RdRua = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        RdCep = new javax.swing.JRadioButton();
        LblEscolha = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtCep = new javax.swing.JTextField();
        txtRua = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        lblImagem = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTablePrefeituras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nome do Cliente", "Telefone", "Celular", "Endereço", "Estado", "Situação"
            }
        ));
        jScrollPane1.setViewportView(jTablePrefeituras);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 274, 890, 307));

        jLabel1.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Consulta de Telefones Prefeituras");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 19, 900, -1));
        getContentPane().add(TxtLinhas, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 241, 93, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Linhas exportadas:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 245, -1, -1));

        JcbEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SP", "MG", "RJ", " " }));
        getContentPane().add(JcbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 197, 93, -1));

        SelecioneGrupo.add(RdEstado);
        RdEstado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RdEstado.setText("Estado");
        RdEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdEstadoActionPerformed(evt);
            }
        });
        getContentPane().add(RdEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, -1));

        SelecioneGrupo.add(RdCidade);
        RdCidade.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RdCidade.setText("Cidade");
        RdCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdCidadeActionPerformed(evt);
            }
        });
        getContentPane().add(RdCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, -1, -1));

        SelecioneGrupo.add(RdRua);
        RdRua.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RdRua.setText("Rua");
        RdRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdRuaActionPerformed(evt);
            }
        });
        getContentPane().add(RdRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Opções de Pesquisa:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 73, 890, -1));

        SelecioneGrupo.add(RdCep);
        RdCep.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RdCep.setText("Cep");
        RdCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdCepActionPerformed(evt);
            }
        });
        getContentPane().add(RdCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, -1, -1));

        LblEscolha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblEscolha.setText(" ");
        getContentPane().add(LblEscolha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 120, -1));

        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 620, -1, -1));

        jButton2.setText("Limpar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 620, 79, -1));
        getContentPane().add(txtCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 197, 130, -1));
        getContentPane().add(txtRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 197, 250, -1));
        getContentPane().add(txtCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 197, 250, -1));

        lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Prime.png"))); // NOI18N
        getContentPane().add(lblImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 240, 210));

        jMenu1.setText("Sair");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(912, 731));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RdEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdEstadoActionPerformed
        if(RdEstado.isSelected())
           
        {
        OcultaCampos();
        LblEscolha.setVisible(true);
        LblEscolha.setText("Selecione o Estado");
        JcbEstado.setVisible(true);
        }
    }//GEN-LAST:event_RdEstadoActionPerformed

    private void RdCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdCidadeActionPerformed
         if(RdCidade.isSelected())
           
        {
        OcultaCampos();
        LblEscolha.setVisible(true);
        LblEscolha.setText("Digite o Cep");
        txtCep.setVisible(true);
        }
    }//GEN-LAST:event_RdCidadeActionPerformed

    private void RdRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdRuaActionPerformed
        if(RdRua.isSelected())
           
        {
        OcultaCampos();
        LblEscolha.setVisible(true);    
        LblEscolha.setText("Digite a Rua");
        txtRua.setVisible(true);
        }
    }//GEN-LAST:event_RdRuaActionPerformed

    private void RdCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdCepActionPerformed
          if(RdCep.isSelected())
           
        {
        OcultaCampos();
        LblEscolha.setVisible(true);    
        LblEscolha.setText("Digite a Cidade");
        txtRua.setVisible(true);
        }
    }//GEN-LAST:event_RdCepActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       OcultaCampos();
       txtCep.setText("");
       txtCidade.setText("");
       txtRua.setText("");
       TxtLinhas.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
     //   preencherTabela("select * from PrefeiturasBrasil");       // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    gravar_ArrayList();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrefeituras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrefeituras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrefeituras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrefeituras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new frmPrefeituras().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(frmPrefeituras.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox JcbEstado;
    private javax.swing.JLabel LblEscolha;
    private javax.swing.JRadioButton RdCep;
    private javax.swing.JRadioButton RdCidade;
    private javax.swing.JRadioButton RdEstado;
    private javax.swing.JRadioButton RdRua;
    private javax.swing.ButtonGroup SelecioneGrupo;
    private javax.swing.JTextField TxtLinhas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePrefeituras;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtRua;
    // End of variables declaration//GEN-END:variables

public void OcultaCampos()
{
txtCep.setVisible(false);
txtCidade.setVisible(false);
txtRua.setVisible(false);
JcbEstado.setVisible(false);
LblEscolha.setVisible(false);
}



  public void gravar_ArrayList() {
        try {
            FileWriter arq = new FileWriter("D:/contato.txt");
            PrintWriter memoria_ram = new PrintWriter(arq);
            
            String Cabecalho = "Nome, Telefone, ETC ";
            String Enter = "";
             memoria_ram.println(Cabecalho);
             memoria_ram.println(Enter);
            for (int i = 0; i < jTablePrefeituras.getRowCount(); i++) {
                       String reg = jTablePrefeituras.getValueAt(i, 0)+ ", "
                        + jTablePrefeituras.getValueAt(i, 1) + ", " + jTablePrefeituras.getValueAt(i, 2) + ";";
                memoria_ram.println(reg);
            }
            arq.flush();
            arq.close();
            JOptionPane.showMessageDialog(this, "Arquivo Salvo!");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e);
        }

    }

     public void preencherTabela(String Sql) {
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{"<html><span style='color:#ef6f53;font-weight: bold;'>Código Fornecedor</span></html>",
            "<html><span style='color:#ef6f53;font-weight: bold;'>Nome</span></html>",
            "<html><span style='color:#ef6f53;font-weight: bold;'>Cod Compra</span></html>"};

        conecta.executaSql(Sql);
        try {
            conecta.rs.first();
            do {

                dados.add(new Object[]{conecta.rs.getInt("CodPrefeitura"), conecta.rs.getString("NomeMunicipioPrefeitura"),
                    conecta.rs.getString("TelefonePrefeitura")});

            } while (conecta.rs.next());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Não foi encontrado lançamentos no período selecionado");

        }

        ModeloTabelas modelo = new ModeloTabelas(dados, Colunas); //Instacia a classe do modelo da Tabela.
        jTablePrefeituras.setModel(modelo);
        jTablePrefeituras.getColumnModel().getColumn(0).setPreferredWidth(124); // Tamanho em pixel da coluna
        jTablePrefeituras.getColumnModel().getColumn(0).setResizable(false);
        jTablePrefeituras.getColumnModel().getColumn(1).setPreferredWidth(190);
        jTablePrefeituras.getColumnModel().getColumn(1).setResizable(false);
        jTablePrefeituras.getColumnModel().getColumn(2).setPreferredWidth(90);
        jTablePrefeituras.getColumnModel().getColumn(2).setResizable(false);
       
        jTablePrefeituras.getTableHeader().setReorderingAllowed(false);
        jTablePrefeituras.setAutoResizeMode(jTablePrefeituras.AUTO_RESIZE_OFF);//Não pode ser redimensionada
        jTablePrefeituras.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }
}
