/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controlador.Mysql;
import Controlador.clsProduto;
import Controlador.clsSetor;
import Modelo.ModelProduto;
import Modelo.ModelSetor;
import Modelo.ModeloTabelas;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Alex
 */
public class frm_Setor extends javax.swing.JFrame {
Mysql conecta;
    ModelSetor objSetor;
    clsSetor controladorSetor;
    
    /**
     * Creates new form frm_cliente
     */
    public frm_Setor() throws Exception {
        initComponents();
         conecta = new Mysql();
         objSetor = new ModelSetor();
         controladorSetor = new clsSetor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JtableSetor = new javax.swing.JTable();
        btnCadastrar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        txtSetor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Código:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, 20));

        txtCod.setEditable(false);
        txtCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodActionPerformed(evt);
            }
        });
        getContentPane().add(txtCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 80, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(75, 146, 219));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Setor");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 40));

        JtableSetor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JtableSetor.setToolTipText("");
        JtableSetor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JtableSetorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JtableSetor);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 330, 140));

        btnCadastrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 90, 30));

        btnSair.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 90, 30));

        txtSetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSetorActionPerformed(evt);
            }
        });
        getContentPane().add(txtSetor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 150, -1));

        jLabel3.setText("Nome Setor:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, 20));

        setSize(new java.awt.Dimension(359, 403));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        if (botao == 0)
        {

        if(preencheObjeto())
        {
            try {
                controladorSetor.Incluir(objSetor);
                preencherTabela("Select * From Setor");
                limparcampos();
            } catch (Exception ex) {
                Logger.getLogger(frm_Setor.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
        }else
        {
         if(preencheObjetoAltera())
        {
            try {
                controladorSetor.Alterar(objSetor);
                preencherTabela("Select * From Setor where CodSetor = '"+Codigo+"'");
                limparcampos();
                botao = 1;
                btnSair.setText("Cancelar");
            } catch (Exception ex) {
                Logger.getLogger(frm_Setor.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
        
        }
          

             // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
     if(botao == 0)
     {
     this.dispose();
     }else
     {
     botao = 0;
     limparcampos();
     preencherTabela("Select * From Setor");
     
     }

               // TODO add your handling code here:
    }//GEN-LAST:event_btnSairActionPerformed

    private void txtSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSetorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSetorActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    preencherTabela("Select * From Setor");        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void JtableSetorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtableSetorMouseClicked
     int linha_selecionada = JtableSetor.getSelectedRow(); // Pega a linha selecionada.
        Codigo = Integer.parseInt((JtableSetor.getValueAt(linha_selecionada, 0).toString()));
        txtCod.setText(JtableSetor.getValueAt(linha_selecionada, 0).toString());
       txtSetor.setText(JtableSetor.getValueAt(linha_selecionada, 1).toString());       
       btnCadastrar.setText("Alterar");
       botao = 1;
       btnSair.setText("Cancelar");
    }//GEN-LAST:event_JtableSetorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Setor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Setor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Setor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Setor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new frm_Setor().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(frm_Setor.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JtableSetor;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnSair;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtSetor;
    // End of variables declaration//GEN-END:variables

    int Codigo, botao = 0;
    
    public void limparcampos ()
    {
    txtCod.setText("");
    txtSetor.setText("");
    btnCadastrar.setText("Cadastrar");
    btnSair.setText("Sair");
    
    
    }
    
 public void preencherTabela(String Sql) {
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{
            "<html><span style='color:#4b92db;font-weight: bold;'>Código Setor</span></html>",
            "<html><span style='color:#4b92db;font-weight: bold;'>Setor</span></html>",

        };

        NumberFormat z = NumberFormat.getCurrencyInstance();
        conecta.executaSql(Sql);
        try {
            conecta.rs.first();
            do {
                dados.add(new Object[]{conecta.rs.getInt("CodSetor"), conecta.rs.getString("NomeSetor")});
            } while (conecta.rs.next());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao preencher a Tabela" + e);

        }

        ModeloTabelas modelo = new ModeloTabelas(dados, Colunas); //Instacia a classe do modelo da Tabela.
        JtableSetor.setModel(modelo);
        JtableSetor.getColumnModel().getColumn(0).setPreferredWidth(161); // Tamanho em pixel da coluna
        JtableSetor.getColumnModel().getColumn(0).setResizable(false);
        JtableSetor.getColumnModel().getColumn(1).setPreferredWidth(162);
        JtableSetor.getColumnModel().getColumn(1).setResizable(false);
  
        JtableSetor.setAutoResizeMode(JtableSetor.AUTO_RESIZE_OFF);//Não pode ser redimensionada
        JtableSetor.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }
    
     public boolean preencheObjeto() {

        objSetor.setNomeSetor(txtSetor.getText());


        return true;
    }
     
          public boolean preencheObjetoAltera() {

        objSetor.setNomeSetor(txtSetor.getText());
        objSetor.setCodSetor(Codigo);

        return true;
    }


}
