/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controlador.Mysql;
import Controlador.clsApartamento;
import Modelo.ModelApartamento;
import Modelo.ModeloTabelas;

import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Alex
 */
public class frm_Apartamento extends javax.swing.JFrame {

    Mysql connCombo;
    Mysql conecta;
    private clsApartamento DAO;
    private Modelo.ModelApartamento ObjLancaApartamento;
    private Modelo.ModelApartamento ObjAlteraApartamento;

    /**
     * Creates new form frm_cliente
     *
     * @throws java.lang.Exception
     */
    public frm_Apartamento() throws Exception {
        initComponents();
        conecta = new Mysql();
        ObjLancaApartamento = new ModelApartamento();
        ObjAlteraApartamento = new ModelApartamento();
        DAO = new clsApartamento();
        rd_Disponivel.setSelected(true);
        connCombo = new Mysql();
        connCombo.getCon();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_descricao = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        rd_Disponivel = new javax.swing.JRadioButton();
        rd_Manutencao = new javax.swing.JRadioButton();
        cmbCategoria = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        JtableApartamento = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Descrição");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 79, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Situação:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        txt_descricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_descricaoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_descricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 76, 270, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Tarifário:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 113, -1, -1));

        buttonGroup1.add(rd_Disponivel);
        rd_Disponivel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rd_Disponivel.setText("Disponível");
        getContentPane().add(rd_Disponivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        buttonGroup1.add(rd_Manutencao);
        rd_Manutencao.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rd_Manutencao.setText("Manutenção");
        getContentPane().add(rd_Manutencao, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));

        cmbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCategoriaActionPerformed(evt);
            }
        });
        getContentPane().add(cmbCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 110, 180, -1));

        JtableApartamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JtableApartamento.setToolTipText("");
        jScrollPane1.setViewportView(JtableApartamento);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 370, 180));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(75, 146, 219));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Apartamentos");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 40));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("Cadastrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 90, 30));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 90, 30));

        setBounds(0, 0, 424, 528);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_descricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_descricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_descricaoActionPerformed

    private void cmbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoriaActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCategoriaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
// TODO add your handling code here:

        preencherCombo();
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
           // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      
                // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Apartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Apartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Apartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Apartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new frm_Apartamento().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(frm_Apartamento.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JtableApartamento;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbCategoria;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rd_Disponivel;
    private javax.swing.JRadioButton rd_Manutencao;
    private javax.swing.JTextField txt_descricao;
    // End of variables declaration//GEN-END:variables

    String Situacao, NomeCategoria;
    int codCategoria;

    public boolean preencheObjeto() {

        ObjLancaApartamento.setDescricao(txt_descricao.getText());
        //     ObjLancaApartamento.setValorDiaria(Double.parseDouble( txt_valor.getText()));//.replace("R$", "").replace(".", "").replace(",",".")
      
        ObjLancaApartamento.setSituacao(Situacao);
        ObjLancaApartamento.setCategoriaApartamento(codCategoria);
        return true;
    }

    public void preencherCombo() {

        connCombo.getCon();
        connCombo.executaSql("select distinct CategoriaApartamento from Categoria");

        try {

            cmbCategoria.removeAllItems();
            connCombo.rs.first();
            cmbCategoria.addItem("<html><span style='color:#583742;font-weight: bold;'>Selecione a Despesa...</span></html>");

            do {
                cmbCategoria.addItem("<html><span style='color:#583742;font-weight: bold;'>" + (connCombo.rs.getString("CategoriaApartamento") + "</span></html>"));

            } while (connCombo.rs.next());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher ComboBox" + e);
        }
    }
    
     public void preencherTabela(String Sql) {
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{
            "<html><span style='color:#4b92db;font-weight: bold;'>Cód Categoria</span></html>",
            "<html><span style='color:#4b92db;font-weight: bold;'>Categoria</span></html>",
            "<html><span style='color:#4b92db;font-weight: bold;'>Máx Hóspedes</span></html>",
            "<html><span style='color:#4b92db;font-weight: bold;'>Valor Diária</span></html>"
        };

        NumberFormat z = NumberFormat.getCurrencyInstance();
        conecta.executaSql(Sql);
        try {
            conecta.rs.first();
            do {
                dados.add(new Object[]{conecta.rs.getInt("CodCategoria"), conecta.rs.getString("CategoriaApto"),conecta.rs.getInt("MaxPax"), z.format(conecta.rs.getDouble("ValorDiaria"))});
            } while (conecta.rs.next());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao preencher a Tabela" + e);

        }

        ModeloTabelas modelo = new ModeloTabelas(dados, Colunas); //Instacia a classe do modelo da Tabela.
        JtableApartamento.setModel(modelo);
        JtableApartamento.getColumnModel().getColumn(0).setPreferredWidth(90); // Tamanho em pixel da coluna
        JtableApartamento.getColumnModel().getColumn(0).setResizable(false);
        JtableApartamento.getColumnModel().getColumn(1).setPreferredWidth(130);
        JtableApartamento.getColumnModel().getColumn(1).setResizable(false);
        JtableApartamento.getColumnModel().getColumn(2).setPreferredWidth(100);
        JtableApartamento.getColumnModel().getColumn(2).setResizable(false);
        JtableApartamento.getColumnModel().getColumn(3).setPreferredWidth(84);
        JtableApartamento.getColumnModel().getColumn(3).setResizable(false);
        JtableApartamento.getTableHeader().setReorderingAllowed(false);
        JtableApartamento.setAutoResizeMode(JtableApartamento.AUTO_RESIZE_OFF);//Não pode ser redimensionada
        JtableApartamento.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }
    

}
