/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controlador.Mysql;
import Controlador.clsCliente;
import Modelo.ModeloTabelas;
import Modelo.modelCliente;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Alex
 */
public class frm_cliente extends javax.swing.JFrame {

    /**
     * Creates new form frm_cliente
     */
    private clsCliente DAO;
    private Modelo.modelCliente ObjLancaCliente;
    private Modelo.modelCliente ObjAlteraCliente;
    Mysql conecta;
    
    SimpleDateFormat fmt;
    
    public frm_cliente() throws Exception {
        initComponents();
        
        ObjAlteraCliente = new modelCliente();
        ObjLancaCliente = new modelCliente();
        DAO = new clsCliente();
        conecta = new Mysql();
        fmt = new SimpleDateFormat("dd/MM/yyyy");
        //preencherTabela("SELECT * FROM CLIENTE");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        JTableCliente = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        mtxt_cpf = new javax.swing.JFormattedTextField();
        Jdate_nascimento = new com.toedter.calendar.JDateChooser();
        mtxt_celular = new javax.swing.JFormattedTextField();
        mtxt_cep = new javax.swing.JFormattedTextField();
        txt_rua = new javax.swing.JTextField();
        txt_numero = new javax.swing.JTextField();
        txt_bairro = new javax.swing.JTextField();
        txt_cidade = new javax.swing.JTextField();
        txt_complemento = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Btn_Cadastrar = new javax.swing.JButton();
        cmb_uf = new javax.swing.JComboBox<>();
        btnCancelar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_senha = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_residencial = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(75, 146, 219));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Cadastro de Hóspedes");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 1190, 40);

        JTableCliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JTableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        JTableCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTableClienteMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(JTableCliente);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(10, 450, 1170, 150);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Nome:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("CPF:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Nascimento:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Celular:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("CEP:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Rua:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Bairro:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Cidade:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Estado:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Nº:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Complemento:");

        txt_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomeActionPerformed(evt);
            }
        });

        try {
            mtxt_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            mtxt_celular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            mtxt_cep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        mtxt_cep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mtxt_cepActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Btn_Cadastrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Btn_Cadastrar.setText("Cadastrar");
        Btn_Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CadastrarActionPerformed(evt);
            }
        });

        cmb_uf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", " ", "SP", "MG", "PR", "RJ", "RN", "SC", " ", " " }));

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Senha:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Email:");

        try {
            txt_residencial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Residencial:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Jdate_nascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel7))
                                .addGap(17, 17, 17)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txt_rua, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabel11)
                                        .addGap(14, 14, 14)
                                        .addComponent(txt_numero))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txt_residencial, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel4)
                                        .addGap(13, 13, 13)
                                        .addComponent(mtxt_celular, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_nome)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(mtxt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Btn_Cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(157, 157, 157)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel8)
                            .addComponent(jLabel14))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mtxt_cep, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(txt_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel9)
                                    .addGap(42, 42, 42)
                                    .addComponent(txt_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cmb_uf, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txt_complemento)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel13)
                                    .addGap(18, 18, 18)
                                    .addComponent(txt_senha))))))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nome)
                    .addComponent(mtxt_cpf)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Jdate_nascimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_residencial)
                    .addComponent(mtxt_celular)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_rua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mtxt_cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_numero)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cmb_uf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_complemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btn_Cadastrar)
                            .addComponent(jButton1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar)))
                .addGap(77, 77, 77))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(200, 70, 780, 350);

        setSize(new java.awt.Dimension(1203, 661));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JTableClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTableClienteMouseClicked
        Botao = 1;
        
        CpfAntigo = (String) JTableCliente.getValueAt(JTableCliente.getSelectedRow(), 0);
        
        System.out.println(CpfAntigo);
        
        int linha_selecionada = JTableCliente.getSelectedRow(); // Pega a linha selecionada.

        String cpf = (String) JTableCliente.getValueAt(JTableCliente.getSelectedRow(), 0);
        
        mtxt_cpf.setText(JTableCliente.getValueAt(linha_selecionada, 0).toString());
        txt_nome.setText(JTableCliente.getValueAt(linha_selecionada, 1).toString());
        
        txt_rua.setText(JTableCliente.getValueAt(linha_selecionada, 5).toString());
        txt_numero.setText(JTableCliente.getValueAt(linha_selecionada, 6).toString());
        mtxt_celular.setText(JTableCliente.getValueAt(linha_selecionada, 3).toString());
        txt_residencial.setText(JTableCliente.getValueAt(linha_selecionada, 4).toString());
        txt_complemento.setText(JTableCliente.getValueAt(linha_selecionada, 7).toString());
        mtxt_cep.setText(JTableCliente.getValueAt(linha_selecionada, 8).toString());
        txt_bairro.setText(JTableCliente.getValueAt(linha_selecionada, 9).toString());
        txt_cidade.setText(JTableCliente.getValueAt(linha_selecionada, 10).toString());
        cmb_uf.setSelectedItem(JTableCliente.getValueAt(linha_selecionada, 11).toString());
        
        txt_email.setText(JTableCliente.getValueAt(linha_selecionada, 12).toString());
        txt_senha.setText(JTableCliente.getValueAt(linha_selecionada, 13).toString());
        
        Btn_Cadastrar.setText("Alterar");
        try {
            Jdate_nascimento.setDate(new SimpleDateFormat("dd/MM/yyyy").parse(JTableCliente.getValueAt(linha_selecionada, 2).toString()));
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "erro " + ex);
        }
        

    }//GEN-LAST:event_JTableClienteMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
    }//GEN-LAST:event_formWindowOpened

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        Btn_Cadastrar.setText("Cadastrar");
        Botao = 0;
          preencherTabela("SELECT * FROM CLIENTE");
      LimparCampos();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void Btn_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CadastrarActionPerformed
        if (Botao == 0){
        if (preencheObjeto()) {
            try {
                DAO.Incluir(ObjLancaCliente);
                String Cpf = mtxt_cpf.getText();
                
                preencherTabela("SELECT * FROM CLIENTE WHERE Cpf_Cliente LIKE '" + Cpf + "'");
                
                LimparCampos();
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Erro ao Lançar dados: " + ex);
            }
            
         }}else{
        if (preencheObjetoAltera()) {
            try {
                
                DAO.Alterar(ObjAlteraCliente);
                String Cpf = mtxt_cpf.getText();
                
                preencherTabela("SELECT * FROM CLIENTE WHERE Cpf_Cliente LIKE '" + Cpf + "'");
                
                LimparCampos();
                Botao = 0;
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Erro ao Lançar dados: " + ex);
            }
            
        }
        }
       

        
        
        

        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_CadastrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void mtxt_cepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mtxt_cepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mtxt_cepActionPerformed

    private void txt_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new frm_cliente().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(frm_cliente.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Cadastrar;
    private javax.swing.JTable JTableCliente;
    private com.toedter.calendar.JDateChooser Jdate_nascimento;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cmb_uf;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JFormattedTextField mtxt_celular;
    private javax.swing.JFormattedTextField mtxt_cep;
    private javax.swing.JFormattedTextField mtxt_cpf;
    private javax.swing.JTextField txt_bairro;
    private javax.swing.JTextField txt_cidade;
    private javax.swing.JTextField txt_complemento;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_numero;
    private javax.swing.JFormattedTextField txt_residencial;
    private javax.swing.JTextField txt_rua;
    private javax.swing.JTextField txt_senha;
    // End of variables declaration//GEN-END:variables
    int Botao = 0;
    String CpfAntigo;
    

    
    
    public boolean preencheObjeto() {
        
        int ano = Jdate_nascimento.getCalendar().get(Calendar.YEAR);
        int mes = Jdate_nascimento.getCalendar().get(Calendar.MONTH) + 1;
        int dia = Jdate_nascimento.getCalendar().get(Calendar.DAY_OF_MONTH);
        String Nascimento = ano + "-" + mes + "-" + dia;
        
        ObjLancaCliente.setCpf_Clien(mtxt_cpf.getText());
        ObjLancaCliente.setNome_Clien(txt_nome.getText());
        ObjLancaCliente.setNasc_Clien(Nascimento);
        ObjLancaCliente.setRua(txt_rua.getText());
        ObjLancaCliente.setN_Resid(txt_numero.getText());
        ObjLancaCliente.setCelular(mtxt_celular.getText());
        ObjLancaCliente.setTelefoneResidencial(txt_residencial.getText());
        ObjLancaCliente.setComplemento(txt_complemento.getText());
        ObjLancaCliente.setCep_Clien(mtxt_cep.getText());
        ObjLancaCliente.setBairro(txt_bairro.getText());
        ObjLancaCliente.setCidade(txt_cidade.getText());
        ObjLancaCliente.setUF((String) cmb_uf.getSelectedItem());
        ObjLancaCliente.setEmail(txt_email.getText());
        ObjLancaCliente.setSenha(txt_senha.getText());
        
        return true;
    }
    
    public boolean preencheObjetoAltera() {
        
        int ano = Jdate_nascimento.getCalendar().get(Calendar.YEAR);
        int mes = Jdate_nascimento.getCalendar().get(Calendar.MONTH) + 1;
        int dia = Jdate_nascimento.getCalendar().get(Calendar.DAY_OF_MONTH);
        String Nascimento = ano + "-" + mes + "-" + dia;
        
        ObjAlteraCliente.setCPFAltera(CpfAntigo);
        ObjAlteraCliente.setCpf_Clien(mtxt_cpf.getText());
        ObjAlteraCliente.setNome_Clien(txt_nome.getText());
        ObjAlteraCliente.setNasc_Clien(Nascimento);
        ObjAlteraCliente.setRua(txt_rua.getText());
        ObjAlteraCliente.setN_Resid(txt_numero.getText());
        ObjAlteraCliente.setCelular(mtxt_celular.getText());
        ObjAlteraCliente.setTelefoneResidencial(txt_residencial.getText());
        ObjAlteraCliente.setComplemento(txt_complemento.getText());
        ObjAlteraCliente.setCep_Clien(mtxt_cep.getText());
        ObjAlteraCliente.setBairro(txt_bairro.getText());
        ObjAlteraCliente.setCidade(txt_cidade.getText());
        ObjAlteraCliente.setUF((String) cmb_uf.getSelectedItem());
        ObjAlteraCliente.setEmail(txt_email.getText());
        ObjAlteraCliente.setSenha(txt_senha.getText());
        
        return true;
    }
    
    public void LimparCampos() {
        mtxt_cpf.setText("");
        txt_nome.setText("");
        txt_rua.setText("");
        txt_numero.setText("");
        mtxt_celular.setText("");
        txt_residencial.setText("");
        txt_complemento.setText("");
        mtxt_cep.setText("");
        txt_bairro.setText("");
        txt_cidade.setText("");
        cmb_uf.setSelectedIndex(0);
        txt_email.setText("");
        txt_senha.setText("");
        Jdate_nascimento.setDate(null);
        Btn_Cadastrar.setText("Cadastrar");
    }
    
    public void preencherTabela(String Sql) {
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{
            "<html><span style='color:#4b92db;font-weight: bold;'>CPF</span></html>",
            "<html><span style='color:#4b92db;font-weight: bold;'>Nome do Cliente</span></html>",
            "<html><span style='color:#4b92db;font-weight: bold;'>Nascimento</span></html>",
            "<html><span style='color:#4b92db;font-weight: bold;'>Celular</span></html>",
            "<html><span style='color:#4b92db;font-weight: bold;'>Telelefone</span></html>",
            "<html><span style='color:#4b92db;font-weight: bold;'>Rua</span></html>",
            "<html><span style='color:#4b92db;font-weight: bold;'>Nº</span></html>",
            "<html><span style='color:#4b92db;font-weight: bold;'>Complemento</span></html>",
            "<html><span style='color:#4b92db;font-weight: bold;'>CEP</span></html>",
            "<html><span style='color:#4b92db;font-weight: bold;'>Bairro</span></html>",
            "<html><span style='color:#4b92db;font-weight: bold;'>Cidade</span></html>",
            "<html><span style='color:#4b92db;font-weight: bold;'>UF</span></html>",
            "<html><span style='color:#4b92db;font-weight: bold;'>Email</span></html>",
            "<html><span style='color:#4b92db;font-weight: bold;'>Senha</span></html>"
        };
        
        NumberFormat z = NumberFormat.getCurrencyInstance();
        conecta.executaSql(Sql);
        try {
            conecta.rs.first();
            do {
                dados.add(new Object[]{conecta.rs.getString("Cpf_Cliente"), conecta.rs.getString("Nome_Clien"), fmt.format(conecta.rs.getDate("Nasc_Clien")), conecta.rs.getString("Celular"), conecta.rs.getString("TelefoneResidencial"), conecta.rs.getString("Rua"), conecta.rs.getString("N_Resid"), conecta.rs.getString("Complemento"), conecta.rs.getString("Cep_Clien"), conecta.rs.getString("Bairro"), conecta.rs.getString("Cidade"), conecta.rs.getString("UF"), conecta.rs.getString("Email"), conecta.rs.getString("Senha")});
            } while (conecta.rs.next());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao preencher a Tabela" + e);
            
        }
        
        ModeloTabelas modelo = new ModeloTabelas(dados, Colunas); //Instacia a classe do modelo da Tabela.
        JTableCliente.setModel(modelo);
        JTableCliente.getColumnModel().getColumn(0).setPreferredWidth(110); // Tamanho em pixel da coluna
        JTableCliente.getColumnModel().getColumn(0).setResizable(false);
        JTableCliente.getColumnModel().getColumn(1).setPreferredWidth(150);
        JTableCliente.getColumnModel().getColumn(1).setResizable(false);
        JTableCliente.getColumnModel().getColumn(2).setPreferredWidth(90);
        JTableCliente.getColumnModel().getColumn(2).setResizable(false);
        JTableCliente.getColumnModel().getColumn(3).setPreferredWidth(115);
        JTableCliente.getColumnModel().getColumn(3).setResizable(false);
        JTableCliente.getColumnModel().getColumn(4).setPreferredWidth(115);
        JTableCliente.getColumnModel().getColumn(4).setResizable(false);
        JTableCliente.getColumnModel().getColumn(5).setPreferredWidth(150);
        JTableCliente.getColumnModel().getColumn(5).setResizable(false);
        JTableCliente.getColumnModel().getColumn(6).setPreferredWidth(60);
        JTableCliente.getColumnModel().getColumn(6).setResizable(false);
        JTableCliente.getColumnModel().getColumn(7).setPreferredWidth(150);
        JTableCliente.getColumnModel().getColumn(7).setResizable(true);
        JTableCliente.getColumnModel().getColumn(8).setPreferredWidth(90);
        JTableCliente.getColumnModel().getColumn(8).setResizable(false);
        JTableCliente.getColumnModel().getColumn(9).setPreferredWidth(110);
        JTableCliente.getColumnModel().getColumn(9).setResizable(false);
        JTableCliente.getColumnModel().getColumn(10).setPreferredWidth(110);
        JTableCliente.getColumnModel().getColumn(10).setResizable(false);
        JTableCliente.getColumnModel().getColumn(11).setPreferredWidth(50);
        JTableCliente.getColumnModel().getColumn(11).setResizable(false);
        JTableCliente.getColumnModel().getColumn(12).setPreferredWidth(150);
        JTableCliente.getColumnModel().getColumn(12).setResizable(false);
        JTableCliente.getColumnModel().getColumn(13).setPreferredWidth(100);
        JTableCliente.getColumnModel().getColumn(13).setResizable(false);
        
        JTableCliente.getTableHeader().setReorderingAllowed(false);
        JTableCliente.setAutoResizeMode(JTableCliente.AUTO_RESIZE_OFF);//Não pode ser redimensionada
        JTableCliente.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
    }
    
}
