/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controlador.Mysql;
import Controlador.clsCategoria;
import Modelo.LimitadorMoeda;
import Modelo.ModelCategoria;
import Modelo.ModeloTabelas;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Alex
 */
public class frm_Categoria extends javax.swing.JFrame {

    private clsCategoria DAO;
    private Modelo.ModelCategoria ObjLancaCategoria;
    private Modelo.ModelCategoria ObjAlteraCategoria;
    Mysql conecta;
    LimitadorMoeda limitadormoeda;

    public frm_Categoria() throws Exception {
        initComponents();
        ObjAlteraCategoria = new ModelCategoria();
        ObjLancaCategoria = new ModelCategoria();
        DAO = new clsCategoria();
        conecta = new Mysql();
        limitadormoeda = new LimitadorMoeda();
        preencherTabela("Select * From Categoria");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txt_categoria = new javax.swing.JTextField();
        btnSair = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        txt_ValorDiaria = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JtableTarifario = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtMaxPess = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Categoria:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, 20));

        txt_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_categoriaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 180, -1));

        btnSair.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, 90, 30));

        btnCadastrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 90, 30));
        getContentPane().add(txt_ValorDiaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 180, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Valor Diária:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 70, 20));

        JtableTarifario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JtableTarifario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        JtableTarifario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JtableTarifarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JtableTarifario);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 410, 190));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(75, 146, 219));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Categorias");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 40));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Max de Pessoas:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 110, -1, 20));
        getContentPane().add(txtMaxPess, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 180, -1));

        setSize(new java.awt.Dimension(442, 473));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_categoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_categoriaActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        if (Botoes == 0) {

            if (preencheObjeto()) {
                try {
                    DAO.Incluir(ObjLancaCategoria);

                    preencherTabela("SELECT * FROM Categoria");
                    limpadados();
                    //LimparCampos();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Erro ao Lançar dados: " + ex);
                }

            }
        } else {
            System.out.println(CodCategoria);

            if (preencheObjetoAltera()) {
                try {
                    DAO.Alterar(ObjAlteraCategoria);

                    preencherTabela("SELECT * FROM Categoria where CodCategoria = '"+CodCategoria+"'");
                    limpadados();
                    //LimparCampos();

                    Botoes = 0;
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Erro ao alterar dados: " + ex);
                }
                
            }

        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void JtableTarifarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtableTarifarioMouseClicked
        Botoes = 1;

        btnCadastrar.setText("Alterar");
        btnSair.setText("Cancelar");

        int linha_selecionada = JtableTarifario.getSelectedRow(); // Pega a linha selecionada   

        CodCategoria = Integer.parseInt(JtableTarifario.getValueAt(linha_selecionada, 0).toString());
        txt_categoria.setText(JtableTarifario.getValueAt(linha_selecionada, 1).toString());
        txtMaxPess.setText(JtableTarifario.getValueAt(linha_selecionada, 2).toString());
        

    }//GEN-LAST:event_JtableTarifarioMouseClicked

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        if(Botoes == 1)
        {
       
        limpadados();
        Botoes = 0;
        }
        else
        {
        this.dispose();
        }
        // TODO     
    }//GEN-LAST:event_btnSairActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        txt_ValorDiaria.setDocument(limitadormoeda);       // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Categoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Categoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Categoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Categoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new frm_Categoria().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(frm_Categoria.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JtableTarifario;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnSair;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField txtMaxPess;
    private javax.swing.JFormattedTextField txt_ValorDiaria;
    private javax.swing.JTextField txt_categoria;
    // End of variables declaration//GEN-END:variables

    int Botoes;
    int CodCategoria;

    public boolean preencheObjeto() {

        ObjLancaCategoria.setCategoriaApartamento(txt_categoria.getText());
        ObjLancaCategoria.setMaxPax(Integer.parseInt(txtMaxPess.getText()));
        ObjLancaCategoria.setValorDiaria(Double.parseDouble(txt_ValorDiaria.getText().replace(".", "").replace(",", ".")));

        return true;
    }

    public boolean preencheObjetoAltera() {

        ObjAlteraCategoria.setCodCategoria(CodCategoria);
        ObjAlteraCategoria.setCategoriaApartamento(txt_categoria.getText());
        ObjAlteraCategoria.setMaxPax(Integer.parseInt(txtMaxPess.getText()));
        ObjAlteraCategoria.setValorDiaria(Double.parseDouble(txt_ValorDiaria.getText().replace(".", "").replace(",", ".")));

        return true;
    }

    public void preencherTabela(String Sql) {
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{
            "<html><span style='color:#4b92db;font-weight: bold;'>Cód Categoria</span></html>",
            "<html><span style='color:#4b92db;font-weight: bold;'>Categoria</span></html>",
            "<html><span style='color:#4b92db;font-weight: bold;'>Máx Hóspedes</span></html>",
            "<html><span style='color:#4b92db;font-weight: bold;'>Valor Diária</span></html>"
        };

        NumberFormat z = NumberFormat.getCurrencyInstance();
        conecta.executaSql(Sql);
        try {
            conecta.rs.first();
            do {
                dados.add(new Object[]{conecta.rs.getInt("CodCategoria"), conecta.rs.getString("CategoriaApto"), conecta.rs.getInt("MaxPax"), z.format(conecta.rs.getDouble("ValorDiaria"))});
            } while (conecta.rs.next());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao preencher a Tabela" + e);

        }

        ModeloTabelas modelo = new ModeloTabelas(dados, Colunas); //Instacia a classe do modelo da Tabela.
        JtableTarifario.setModel(modelo);
        JtableTarifario.getColumnModel().getColumn(0).setPreferredWidth(90); // Tamanho em pixel da coluna
        JtableTarifario.getColumnModel().getColumn(0).setResizable(false);
        JtableTarifario.getColumnModel().getColumn(1).setPreferredWidth(130);
        JtableTarifario.getColumnModel().getColumn(1).setResizable(false);
        JtableTarifario.getColumnModel().getColumn(2).setPreferredWidth(100);
        JtableTarifario.getColumnModel().getColumn(2).setResizable(false);
        JtableTarifario.getColumnModel().getColumn(3).setPreferredWidth(84);
        JtableTarifario.getColumnModel().getColumn(3).setResizable(false);
        JtableTarifario.getTableHeader().setReorderingAllowed(false);
        JtableTarifario.setAutoResizeMode(JtableTarifario.AUTO_RESIZE_OFF);//Não pode ser redimensionada
        JtableTarifario.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }

    
    public void limpadados(){
        txtMaxPess.setText("");
        txt_ValorDiaria.setText("");
        txt_categoria.setText("");
        txt_categoria.requestFocus();
        btnCadastrar.setText("Cadastrar");
        btnSair.setText("Sair");
    
    }
}
