/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controlador.Mysql;
import Controlador.clsProduto;
import Modelo.LimitadorMoeda;
import Modelo.ModelProduto;
import Modelo.ModeloTabelas;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Alex
 */
public class frm_produto extends javax.swing.JFrame {

    Mysql conecta;
    Mysql connCombo;
    clsProduto controlProduto;
    ModelProduto objProduto;
    LimitadorMoeda limitadormoeda;

    /**
     * Creates new form frm_cliente
     */
    public frm_produto() throws Exception {
        initComponents();
        conecta = new Mysql();
        connCombo = new Mysql();
        controlProduto = new clsProduto();
        objProduto = new ModelProduto();
        limitadormoeda = new LimitadorMoeda();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNomeProduto = new javax.swing.JTextField();
        txtValor = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        rdAtivo = new javax.swing.JRadioButton();
        rdInativo = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JtableProdutos = new javax.swing.JTable();
        btnCadastrar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        cmbSetor = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Nome Produto:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Situação:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 203, -1, -1));

        txtNomeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(txtNomeProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 270, -1));
        getContentPane().add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 100, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Setor:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, 20));

        buttonGroup1.add(rdAtivo);
        rdAtivo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rdAtivo.setText("Ativo");
        rdAtivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdAtivoActionPerformed(evt);
            }
        });
        getContentPane().add(rdAtivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, -1));

        buttonGroup1.add(rdInativo);
        rdInativo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rdInativo.setText("Inativo");
        rdInativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdInativoActionPerformed(evt);
            }
        });
        getContentPane().add(rdInativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(75, 146, 219));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Produtos");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 40));

        JtableProdutos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JtableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JtableProdutos.setToolTipText("");
        JtableProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JtableProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JtableProdutos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 450, 140));

        btnCadastrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 90, 30));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 90, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Valor:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, 20));

        cmbSetor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione..." }));
        cmbSetor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbSetorMouseClicked(evt);
            }
        });
        cmbSetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSetorActionPerformed(evt);
            }
        });
        getContentPane().add(cmbSetor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 200, -1));

        setSize(new java.awt.Dimension(483, 514));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeProdutoActionPerformed

    private void rdInativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdInativoActionPerformed
    situacao = "I";        // TODO add your handling code here:
    }//GEN-LAST:event_rdInativoActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        try {
            String nomesetor = cmbSetor.getSelectedItem().toString().substring(53).replace("</span></html>", "");
            conecta.executaSql("select * from Setor where NomeSetor = '" + nomesetor + "'");

            conecta.rs.first();
            setor = (conecta.rs.getInt("CodSetor"));
            
        } catch (SQLException ex) {
            System.out.println("Reseva não encontrado");
            ex.printStackTrace();
        }
        
        if(botao == 0)
        {
        
        if(preencheObjeto())
        {
            try {
                controlProduto.Incluir(objProduto);
            } catch (Exception ex) {
               JOptionPane.showMessageDialog(null, "Erro ao inserir Produto "+ex);
            }
            preencherTabela("Select * from Produto as p join Setor as s on s.CodSetor = p.CodSetor and Situacao = 'A'");
             limparCampos();
            
        }
        }else{
            
                 if(preencheObjetoAltera())
        {
            try {
                controlProduto.Alterar(objProduto);
            } catch (Exception ex) {
               JOptionPane.showMessageDialog(null, "Erro ao Alterar Produto "+ex);
            }
            preencherTabela("Select * from Produto as p join Setor as s on s.CodSetor = p.CodSetor where Cod_Produto = '"+Codigo+"' ");
            botao = 0;
             limparCampos();
        }   
            
            
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        botao = 0;
        btnCadastrar.setText("Cadastrar");
        limparCampos();
          preencherTabela("Select * from Produto as p join Setor as s on s.CodSetor = p.CodSetor and Situacao = 'A'");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        rdAtivo.setSelected(true);
        txtValor.setDocument(limitadormoeda);   
         preencherTabela("Select * from Produto as p join Setor as s on s.CodSetor = p.CodSetor and Situacao = 'A'");
        preencherCombo();// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void cmbSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSetorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSetorActionPerformed

    private void cmbSetorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbSetorMouseClicked

    }//GEN-LAST:event_cmbSetorMouseClicked

    private void rdAtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdAtivoActionPerformed
    situacao = "A";        // TODO add your handling code here:
    }//GEN-LAST:event_rdAtivoActionPerformed

    private void JtableProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtableProdutosMouseClicked
        int linha_selecionada = JtableProdutos.getSelectedRow(); // Pega a linha selecionada.
        Codigo = Integer.parseInt((JtableProdutos.getValueAt(linha_selecionada, 0).toString()));    
        txtNomeProduto.setText(JtableProdutos.getValueAt(linha_selecionada,1).toString());
        String Setor = (JtableProdutos.getValueAt(linha_selecionada, 4).toString());
        System.out.println(Setor);
        cmbSetor.setSelectedItem(Setor);
        btnCadastrar.setText("Alterar");
         botao = 1;
        // TODO add your handling code here:
    }//GEN-LAST:event_JtableProdutosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new frm_produto().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(frm_produto.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JtableProdutos;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbSetor;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdAtivo;
    private javax.swing.JRadioButton rdInativo;
    private javax.swing.JTextField txtNomeProduto;
    private javax.swing.JFormattedTextField txtValor;
    // End of variables declaration//GEN-END:variables
    int Codigo, botao = 0, setor;
    String situacao = "A";

    public void limparcampos() {
        txtNomeProduto.setText("");
        txtValor.setText("");
        cmbSetor.setSelectedIndex(1);
        //btnSair.setText("Sair");

    }

    public void preencherTabela(String Sql) {
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{
            "<html><span style='color:#4b92db;font-weight: bold;'>Código</span></html>",
            "<html><span style='color:#4b92db;font-weight: bold;'>Nome</span></html>",
            "<html><span style='color:#4b92db;font-weight: bold;'>Valor</span></html>",
            "<html><span style='color:#4b92db;font-weight: bold;'>Situação</span></html>",
            "<html><span style='color:#4b92db;font-weight: bold;'>Setor</span></html>"
        };

        NumberFormat z = NumberFormat.getCurrencyInstance();
        conecta.executaSql(Sql);
        try {
            conecta.rs.first();
            do {
                dados.add(new Object[]{conecta.rs.getInt("Cod_Produto"), conecta.rs.getString("Nome_Produto"), z.format(conecta.rs.getDouble("Valor_Produto")), conecta.rs.getString("Situacao"), conecta.rs.getString("NomeSetor")});
            } while (conecta.rs.next());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao preencher a Tabela" + e);

        }

        ModeloTabelas modelo = new ModeloTabelas(dados, Colunas); //Instacia a classe do modelo da Tabela.
        JtableProdutos.setModel(modelo);
        JtableProdutos.getColumnModel().getColumn(0).setPreferredWidth(55); // Tamanho em pixel da coluna
        JtableProdutos.getColumnModel().getColumn(0).setResizable(false);
        JtableProdutos.getColumnModel().getColumn(1).setPreferredWidth(130);
        JtableProdutos.getColumnModel().getColumn(1).setResizable(false);
        JtableProdutos.getColumnModel().getColumn(2).setPreferredWidth(100);
        JtableProdutos.getColumnModel().getColumn(2).setResizable(false);
        JtableProdutos.getColumnModel().getColumn(3).setPreferredWidth(65);
        JtableProdutos.getColumnModel().getColumn(3).setResizable(false);
        JtableProdutos.getColumnModel().getColumn(4).setPreferredWidth(94);
        JtableProdutos.getColumnModel().getColumn(4).setResizable(false);
        JtableProdutos.getTableHeader().setReorderingAllowed(false);
        JtableProdutos.setAutoResizeMode(JtableProdutos.AUTO_RESIZE_OFF);//Não pode ser redimensionada
        JtableProdutos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }

    public void preencherCombo() {

        connCombo.getCon();
        connCombo.executaSql("select distinct NomeSetor from Setor");

        try {

            cmbSetor.removeAllItems();
            connCombo.rs.first();
            cmbSetor.addItem("<html><span style='color:#4b92db;font-weight: bold;'>Selecione o Setor...</span></html>");

            do {
                cmbSetor.addItem("<html><span style='color:#4b92db;font-weight: bold;'>" + (connCombo.rs.getString("NomeSetor") + "</span></html>"));

            } while (connCombo.rs.next());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher ComboBox" + e);
        }
    }

    public boolean preencheObjeto() {

        objProduto.setNomeProduto(txtNomeProduto.getText());
        objProduto.setValorProduto(Double.parseDouble(txtValor.getText().replace(".", "").replace(",", ".")));
        objProduto.setCodSetor(setor);
        objProduto.setSituacaoProduto(situacao);
        
        return true;
    }
    


    public boolean preencheObjetoAltera() {
        objProduto.setCodProduto(Codigo);
        objProduto.setNomeProduto(txtNomeProduto.getText());
        objProduto.setValorProduto(Double.parseDouble(txtValor.getText().replace(".", "").replace(",", ".")));
        objProduto.setCodSetor(setor);
        objProduto.setSituacaoProduto(situacao);
        
        return true;
    }

    public void limparCampos(){
    txtNomeProduto.setText("");
    txtValor.setText(null);
    cmbSetor.setSelectedIndex(0);
    rdAtivo.setSelected(true);
    txtNomeProduto.requestFocus();
    }
}
