/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controlador.Mysql;
import Controlador.clsReserva;
import Modelo.ModeloReserva;
import Modelo.ModeloTabelas;
import static Visao.frmLogin.codFuncionario;
import static Visao.frmLogin.nomeFuncionario;
import static Visao.frmLogin.setPermissaoFunci;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Alex
 */
public class frmReservas extends javax.swing.JFrame {

    Modelo.ModeloReserva ModeloReserva;
    Controlador.clsReserva DAO;
    Mysql conecta;
    clsReserva retornso;
    SimpleDateFormat fmt;
    Mysql connCombo;

    /**
     * Creates new form frmReservas
     */
    public frmReservas() throws Exception {
        initComponents();
        DAO = new clsReserva();
        ModeloReserva = new ModeloReserva();
        conecta = new Mysql();
        fmt = new SimpleDateFormat("dd/MM/yyyy");
        connCombo = new Mysql();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        JtableAcompa = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        JTableReserva = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbApartamento = new javax.swing.JComboBox<>();
        mtxt_cpf = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        JdateCheckin = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JdateCheckout = new com.toedter.calendar.JDateChooser();
        txtTotal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtCpfAcmp = new javax.swing.JFormattedTextField();
        txtNomeAcmp = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        JdateNascAssociado = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        JtableAcmp = new javax.swing.JTable();
        btnAssociado = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        JDatecheckoutBusca = new com.toedter.calendar.JDateChooser();
        JdateCheckinBusca = new com.toedter.calendar.JDateChooser();
        BtnPesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(75, 146, 219));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Reservas");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 40));

        JtableAcompa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JtableAcompa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(JtableAcompa);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 560, 480, 99));

        JTableReserva.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JTableReserva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        JTableReserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTableReservaMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(JTableReserva);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 980, 99));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Reserva", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(75, 146, 219))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Apartamento:");

        cmbApartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione..." }));

        try {
            mtxt_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        mtxt_cpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                mtxt_cpfFocusLost(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("CPF:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Nome:");

        txtNome.setEditable(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Check In:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Check Out:");

        JdateCheckout.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JdateCheckoutFocusLost(evt);
            }
        });

        txtTotal.setEditable(false);
        txtTotal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTotalFocusGained(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Total:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Acompanhantes?");

        buttonGroup1.add(jCheckBox1);
        jCheckBox1.setText("Sim");
        jCheckBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox1MouseClicked(evt);
            }
        });

        buttonGroup1.add(jCheckBox2);
        jCheckBox2.setSelected(true);
        jCheckBox2.setText("Não");
        jCheckBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBox2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel6)))
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbApartamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(mtxt_cpf)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(jLabel8)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JdateCheckin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JdateCheckout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbApartamento))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mtxt_cpf)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JdateCheckin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JdateCheckout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2))
                .addGap(28, 28, 28))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 470, 280));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Inclusão de Acompanhantes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(75, 146, 219))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("CPF:");

        try {
            txtCpfAcmp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Nome:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Nascimento:");

        JtableAcmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(JtableAcmp);

        btnAssociado.setText("Incluir");
        btnAssociado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssociadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JdateNascAssociado, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomeAcmp, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel10)
                        .addGap(21, 21, 21)
                        .addComponent(txtCpfAcmp, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAssociado, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(186, 186, 186))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCpfAcmp)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeAcmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JdateNascAssociado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAssociado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 470, 280));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, 110, 40));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("Incluir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 110, 40));
        getContentPane().add(JDatecheckoutBusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, 160, -1));
        getContentPane().add(JdateCheckinBusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 160, -1));

        BtnPesquisar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnPesquisar.setText("Pesquisar");
        BtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 400, -1, -1));

        setSize(new java.awt.Dimension(1002, 720));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssociadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssociadoActionPerformed
    

        if (preencheObjeto()) {
            try {
                DAO.Incluir(ModeloReserva);

              
                try {
                    conecta.rs.first();
                

                
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Erro ao inserir Acompanhante: " + ex);
                }

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Erro ao Lançar dados: " + ex);
            }
            preencherTabelaAcomp("select * from acompanhantes where CodReserva = '"+codreserva+"' order by cod_acmp desc limit 1");
        }

// TODO add your handling code here:
    }//GEN-LAST:event_btnAssociadoActionPerformed

    private void jCheckBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox2MouseClicked
        txtCpfAcmp.setEnabled(false);
        txtNomeAcmp.setEnabled(false);
        JdateNascAssociado.setEnabled(false);
        btnAssociado.setEnabled(false);
    }//GEN-LAST:event_jCheckBox2MouseClicked

    private void jCheckBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox1MouseClicked
        txtCpfAcmp.setEnabled(true);
        txtNomeAcmp.setEnabled(true);
        JdateNascAssociado.setEnabled(true);
        btnAssociado.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        conecta.getConexao();
        codUsuario = frmLogin.getCodFuncionario();
       // preencherTabelaReserva("select * from Reserva as r join Comanda as co on co.Cod_Reserva = r.Cod_Reserva join Apartamento as a on a.Cod_AP = r.Cod_Apto join Cliente as c on c.Cpf_Cliente = r.Cpf_Cliente join Usuario as u on u.CodUsuario = r.CodUsuario");
        preencherCombo();
        txtCpfAcmp.setEnabled(false);
        txtNomeAcmp.setEnabled(false);
        JdateNascAssociado.setEnabled(false);
        btnAssociado.setEnabled(false);
         
        try {

            conecta.executaSql("select * from Reserva");

            conecta.rs.first();
            codreserva = (conecta.rs.getInt("Cod_Reserva"));

        } catch (SQLException ex) {
            System.out.println("Reseva não encontrado");
            ex.printStackTrace();
        }
         codreserva++;
       
        System.out.println(codreserva);

// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void mtxt_cpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mtxt_cpfFocusLost
        String nome;
        try {

            conecta.executaSql("select * from Cliente where Cpf_Cliente = '" + mtxt_cpf.getText() + "'");

            conecta.rs.first();
            nome = (conecta.rs.getString("Nome_Clien"));
            txtNome.setText(nome);
           // conecta.desconecta();

        } catch (SQLException ex) {
            System.out.println("Cliente não encontrado");
            ex.printStackTrace();
        }

    }//GEN-LAST:event_mtxt_cpfFocusLost

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (preencheObjetoReserva()) {
            try {
                DAO.IncluirReserva(ModeloReserva);
                
              
                
                preencherTabelaReserva("select * from Reserva as r join Comanda as co on co.Cod_Reserva = r.Cod_Reserva join Apartamento as a on a.Cod_AP = r.Cod_Apto join Cliente as c on c.Cpf_Cliente = r.Cpf_Cliente join Usuario as u on u.CodUsuario = r.CodUsuario");

               LimparCampos();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Erro ao Incluir Reserva: " + ex);
            }
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void JdateCheckoutFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JdateCheckoutFocusLost

    }//GEN-LAST:event_JdateCheckoutFocusLost

    private void txtTotalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTotalFocusGained
        if (JdateCheckin.getDate() != null || JdateCheckout != null || cmbApartamento.getSelectedIndex() != 0) {
            int Diarias = difDatas(JdateCheckin.getDate(), JdateCheckout.getDate());
            Diarias --;
            try {

                int codApartamento = Integer.parseInt(cmbApartamento.getSelectedItem().toString().substring(53).replace("</span></html>", ""));
                conecta.executaSql("select ValorDiaria from Categoria as c join Apartamento as A on a.Cod_Categoria = c.CodCategoria and Cod_AP = '" + codApartamento + "'");

                conecta.rs.first();
                double valorDiaria = (conecta.rs.getDouble("ValorDiaria"));
                txtTotal.setText("" + Diarias * valorDiaria);

            } catch (SQLException ex) {
                System.out.println("Cliente não encontrado");
                ex.printStackTrace();
            }

        }
    }//GEN-LAST:event_txtTotalFocusGained

    private void JTableReservaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTableReservaMouseClicked
     int linha_selecionada = JTableReserva.getSelectedRow(); // Pega a linha selecionada   

       int Codigo = Integer.parseInt(JTableReserva.getValueAt(linha_selecionada, 0).toString());  
      
        preencherTabelaAcompreser("select * from acompanhantes where CodReserva = '"+Codigo+"'");
    }//GEN-LAST:event_JTableReservaMouseClicked

    private void BtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPesquisarActionPerformed
    
        int anob = JdateCheckinBusca.getCalendar().get(Calendar.YEAR);
        int mesb = JdateCheckinBusca.getCalendar().get(Calendar.MONTH) + 1;
        int diab = JdateCheckinBusca.getCalendar().get(Calendar.DAY_OF_MONTH);
        Checkinb = anob + "-" + mesb + "-" + diab;
        
        int anos = JDatecheckoutBusca.getCalendar().get(Calendar.YEAR);
        int mess = JDatecheckoutBusca.getCalendar().get(Calendar.MONTH) + 1;
        int dias = JDatecheckoutBusca.getCalendar().get(Calendar.DAY_OF_MONTH);
        checkoutb = anos + "-" + mess + "-" + dias;   
            
        System.out.println(Checkinb);
        System.out.println(checkoutb);
                preencherTabelaReserva("select * from Reserva as r join Comanda as co on co.Cod_Reserva = r.Cod_Reserva join Apartamento as a on a.Cod_AP = r.Cod_Apto join Cliente as c on c.Cpf_Cliente = r.Cpf_Cliente join Usuario as u on u.CodUsuario = r.CodUsuario where CheckIn between '"+Checkinb+"' and '"+checkoutb+"'");


// TODO add your handling code here:
    }//GEN-LAST:event_BtnPesquisarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            LimparCampos();
            
               try {

            conecta.executaSql("select * from Reserva");

            conecta.rs.first();
            codreserva = (conecta.rs.getInt("Cod_Reserva"));

        } catch (SQLException ex) {
            System.out.println("Reseva não encontrado");
            ex.printStackTrace();
        }
         codreserva++;
            
    }//GEN-LAST:event_jButton3ActionPerformed

    public void setTxtNome(JTextField txtNome) {
        this.txtNome = txtNome;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new frmReservas().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(frmReservas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnPesquisar;
    private com.toedter.calendar.JDateChooser JDatecheckoutBusca;
    private javax.swing.JTable JTableReserva;
    private com.toedter.calendar.JDateChooser JdateCheckin;
    private com.toedter.calendar.JDateChooser JdateCheckinBusca;
    private com.toedter.calendar.JDateChooser JdateCheckout;
    private com.toedter.calendar.JDateChooser JdateNascAssociado;
    private javax.swing.JTable JtableAcmp;
    private javax.swing.JTable JtableAcompa;
    private javax.swing.JButton btnAssociado;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbApartamento;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JFormattedTextField mtxt_cpf;
    private javax.swing.JFormattedTextField txtCpfAcmp;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomeAcmp;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
    int difTempo, codreserva, codUsuario;
       String Checkinb, checkoutb;

    public boolean preencheObjeto() {
        int ano = JdateNascAssociado.getCalendar().get(Calendar.YEAR);
        int mes = JdateNascAssociado.getCalendar().get(Calendar.MONTH) + 1;
        int dia = JdateNascAssociado.getCalendar().get(Calendar.DAY_OF_MONTH);
        String NascimentoAssociado = ano + "-" + mes + "-" + dia;

        ModeloReserva.setCpfAssociado(txtCpfAcmp.getText());
        ModeloReserva.setNomeAssociado(txtNomeAcmp.getText());
        ModeloReserva.setNascAssociado(NascimentoAssociado);
        ModeloReserva.setCodReserva(codreserva);
        return true;
    }
    
    
        public boolean preencheObjetoReserva() {
        int anoc = JdateCheckin.getCalendar().get(Calendar.YEAR);
        int mesc = JdateCheckin.getCalendar().get(Calendar.MONTH) + 1;
        int diac = JdateCheckin.getCalendar().get(Calendar.DAY_OF_MONTH);
        String Checkin = anoc + "-" + mesc + "-" + diac;
        
        int anoo = JdateCheckin.getCalendar().get(Calendar.YEAR);
        int meso = JdateCheckin.getCalendar().get(Calendar.MONTH) + 1;
        int diao = JdateCheckin.getCalendar().get(Calendar.DAY_OF_MONTH);
        String checkout = anoo + "-" + meso + "-" + diao;

        ModeloReserva.setCheckin(Checkin);
        ModeloReserva.setCheckout(checkout);
        ModeloReserva.setCpf(mtxt_cpf.getText());
        ModeloReserva.setTotalreserva(Double.parseDouble((txtTotal.getText())));
        ModeloReserva.setTotalComanda(Double.parseDouble("0.00"));
        ModeloReserva.setCodUsuario(codUsuario);
        ModeloReserva.setCodApto(Integer.parseInt(cmbApartamento.getSelectedItem().toString().substring(53).replace("</span></html>", "")));
        
        return true;
    }

    public void preencherTabelaAcomp(String Sql) {
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{
            "<html><span style='color:#4b92db;font-weight: bold;'>Código</span></html>",
            "<html><span style='color:#4b92db;font-weight: bold;'>CPF</span></html>",
            "<html><span style='color:#4b92db;font-weight: bold;'>Nome</span></html>",
            "<html><span style='color:#4b92db;font-weight: bold;'>Nascimento</span></html>"

        };

        NumberFormat z = NumberFormat.getCurrencyInstance();
        conecta.executaSql(Sql);
        try {
            conecta.rs.first();
            do {
                dados.add(new Object[]{conecta.rs.getInt("Cod_Acmp"), conecta.rs.getString("Cpf_Acmp"), conecta.rs.getString("Nome_Acmp"), fmt.format(conecta.rs.getDate("Nasc_Acmp"))});
            } while (conecta.rs.next());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao preencher a Tabela" + e);

        }

        ModeloTabelas modelo = new ModeloTabelas(dados, Colunas); //Instacia a classe do modelo da Tabela.
        JtableAcmp.setModel(modelo);
        JtableAcmp.getColumnModel().getColumn(0).setPreferredWidth(58); // Tamanho em pixel da coluna
        JtableAcmp.getColumnModel().getColumn(0).setResizable(false);
        JtableAcmp.getColumnModel().getColumn(1).setPreferredWidth(100);
        JtableAcmp.getColumnModel().getColumn(1).setResizable(false);
        JtableAcmp.getColumnModel().getColumn(2).setPreferredWidth(150);
        JtableAcmp.getColumnModel().getColumn(2).setResizable(false);
        JtableAcmp.getColumnModel().getColumn(3).setPreferredWidth(100);
        JtableAcmp.getColumnModel().getColumn(3).setResizable(false);
        JtableAcmp.setAutoResizeMode(JtableAcmp.AUTO_RESIZE_OFF);//Não pode ser redimensionada
        JtableAcmp.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }

       public void preencherTabelaAcompreser(String Sql) {
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{
            "<html><span style='color:#4b92db;font-weight: bold;'>Código</span></html>",
            "<html><span style='color:#4b92db;font-weight: bold;'>CPF</span></html>",
            "<html><span style='color:#4b92db;font-weight: bold;'>Nome</span></html>",
            "<html><span style='color:#4b92db;font-weight: bold;'>Nascimento</span></html>"

        };

        NumberFormat z = NumberFormat.getCurrencyInstance();
        conecta.executaSql(Sql);
        try {
            conecta.rs.first();
            do {
                dados.add(new Object[]{conecta.rs.getInt("Cod_Acmp"), conecta.rs.getString("Cpf_Acmp"), conecta.rs.getString("Nome_Acmp"), fmt.format(conecta.rs.getDate("Nasc_Acmp"))});
            } while (conecta.rs.next());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao preencher a Tabela" + e);

        }

        ModeloTabelas modelo = new ModeloTabelas(dados, Colunas); //Instacia a classe do modelo da Tabela.
        JtableAcompa.setModel(modelo);
        JtableAcompa.getColumnModel().getColumn(0).setPreferredWidth(63); // Tamanho em pixel da coluna
        JtableAcompa.getColumnModel().getColumn(0).setResizable(false);
        JtableAcompa.getColumnModel().getColumn(1).setPreferredWidth(110);
        JtableAcompa.getColumnModel().getColumn(1).setResizable(false);
        JtableAcompa.getColumnModel().getColumn(2).setPreferredWidth(200);
        JtableAcompa.getColumnModel().getColumn(2).setResizable(false);
        JtableAcompa.getColumnModel().getColumn(3).setPreferredWidth(100);
        JtableAcompa.getColumnModel().getColumn(3).setResizable(false);
        JtableAcompa.setAutoResizeMode(JtableAcompa.AUTO_RESIZE_OFF);//Não pode ser redimensionada
        JtableAcompa.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }

    
    public void preencherTabelaReserva(String Sql) {
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{
            "<html><span style='color:#4b92db;font-weight: bold;'>Código</span></html>",
            "<html><span style='color:#4b92db;font-weight: bold;'>Nome</span></html>",
            "<html><span style='color:#4b92db;font-weight: bold;'>CheckIn</span></html>",
            "<html><span style='color:#4b92db;font-weight: bold;'>CheckOut</span></html>",
            "<html><span style='color:#4b92db;font-weight: bold;'>Total</span></html>",
            "<html><span style='color:#4b92db;font-weight: bold;'>Cod_Apto</span></html>",
            "<html><span style='color:#4b92db;font-weight: bold;'>Usuário</span></html>",
            "<html><span style='color:#4b92db;font-weight: bold;'>Comanda</span></html>",
            "<html><span style='color:#4b92db;font-weight: bold;'>Total Comanda</span></html>",};

        NumberFormat z = NumberFormat.getCurrencyInstance();
        conecta.executaSql(Sql);
        try {
            conecta.rs.first();
            do {
                dados.add(new Object[]{conecta.rs.getInt("Cod_Reserva"), conecta.rs.getString("Nome_Clien"), fmt.format(conecta.rs.getDate("CheckIn")), fmt.format(conecta.rs.getDate("CheckOut")), z.format(conecta.rs.getDouble("Total")),
                    conecta.rs.getInt("Cod_AP"), conecta.rs.getString("NomeUsuario"), conecta.rs.getInt("Cod_Comanda"), z.format(conecta.rs.getDouble("Total_Comanda"))});
            } while (conecta.rs.next());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao preencher a Tabela" + e);

        }

        ModeloTabelas modelo = new ModeloTabelas(dados, Colunas); //Instacia a classe do modelo da Tabela.
        JTableReserva.setModel(modelo);
        JTableReserva.getColumnModel().getColumn(0).setPreferredWidth(70); // Tamanho em pixel da coluna
        JTableReserva.getColumnModel().getColumn(0).setResizable(false);
        JTableReserva.getColumnModel().getColumn(1).setPreferredWidth(162);
        JTableReserva.getColumnModel().getColumn(1).setResizable(false);
        JTableReserva.getColumnModel().getColumn(2).setPreferredWidth(90);
        JTableReserva.getColumnModel().getColumn(2).setResizable(false);
        JTableReserva.getColumnModel().getColumn(3).setPreferredWidth(90);
        JTableReserva.getColumnModel().getColumn(3).setResizable(false);
        JTableReserva.getColumnModel().getColumn(4).setPreferredWidth(100);
        JTableReserva.getColumnModel().getColumn(4).setResizable(false);
        JTableReserva.getColumnModel().getColumn(5).setPreferredWidth(70);
        JTableReserva.getColumnModel().getColumn(5).setResizable(false);
        JTableReserva.getColumnModel().getColumn(6).setPreferredWidth(162);
        JTableReserva.getColumnModel().getColumn(6).setResizable(false);
        JTableReserva.getColumnModel().getColumn(7).setPreferredWidth(70);
        JTableReserva.getColumnModel().getColumn(7).setResizable(false);
        JTableReserva.getColumnModel().getColumn(8).setPreferredWidth(157);
        JTableReserva.getColumnModel().getColumn(8).setResizable(false);

        JTableReserva.setAutoResizeMode(JTableReserva.AUTO_RESIZE_OFF);//Não pode ser redimensionada
        JTableReserva.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }

    public void preencherCombo() {

        connCombo.getCon();
        connCombo.executaSql("select distinct Cod_AP from Apartamento");

        try {

            cmbApartamento.removeAllItems();
            connCombo.rs.first();
            cmbApartamento.addItem("<html><span style='color:#4b92db;font-weight: bold;'>Selecione o Apartamento...</span></html>");

            do {
                cmbApartamento.addItem("<html><span style='color:#4b92db;font-weight: bold;'>" + (connCombo.rs.getInt("Cod_AP") + "</span></html>"));

            } while (connCombo.rs.next());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher ComboBox" + e);
        }
    }

    public static int difDatas(Date dt1, Date dt2) {
        long tempo1 = dt1.getTime();
        long tempo2 = dt2.getTime();
        long difTempo = tempo2 - tempo1;
        return (int) ((difTempo + 60L * 60 * 1000) / (24L * 60 * 60 * 1000)) + 1;
    }

    
    public void LimparCampos (){
    txtCpfAcmp.setText("");
    txtNome.setText("");
    txtNomeAcmp.setText("");
    txtTotal.setText("");
    JDatecheckoutBusca.setDate(null);
    JdateCheckin.setDate(null);
    JdateCheckinBusca.setDate(null);
    JdateCheckout.setDate(null);
    JdateNascAssociado.setDate(null);
    }
}
